"use strict"

$(document).ready(function() {
  // List slide down
  $('h1').click(function() {
    $(this).next('.list').slideToggle(200);
  });

  // show all tabs
  $('div.showAll').click(function() {
    $('div.list').show();
  })

  // close all tabs
  $('div.closeAll').click(function() {
    $('div.list').hide();
  })
  // Tooltips for Japanese names
  $('span').tooltip();

  // Prepare tooltip contents
  $('span').each(function() {
    $(this).prop('title', findName($(this).html()));
  })
});

function findName(eng) {
  for (let name in translation) {
    if (translation[name] === eng) {
      return name;
    }
  }
  console.log(eng + ' was not found');
  return '???'
}

const translation = {
    "ヴァン": "Ally: Vaan",
    "バルフレア": "Ally: Balthier",
    "フラン": "Ally: Fran",
    "バッシュ": "Ally: Basch",
    "アーシェ": "Ally: Ashe",
    "パンネロ": "Ally: Penelo",
    "ラーサー": "Larsa",
    "ウォースラ": "Vossler",
    "レダス": "Reddas",
    "アルシド": "Al-Cid",
    "レックス": "Reks",
    "バッガモナン": "Ba'Gamnan",
    "シドルファス": "Cidolfus",
    "ダラン爺": "Dalan",
    "エルザ": "Elza",
    "フィロ": "Filo",
    "ゲルン王": "Gerun",
    "グラミス": "Gramis",
    "大僧正アナスタシス": "Anastasis",
    "ハバーロ": "Havharo",
    "マッケンロー": "Ma'kenroh",
    "Menu?Edit": "",
    "Japanese?": "Wiki-translation?",
    "バトルメンバー": "Party",
    "ステータス": "Status",
    "装備": "Equip",
    "ライセンス": "Licenses",
    "ガンビット": "Gambits",
    "ワールドマップ": "World Map",
    "所持品リスト": "Inventory",
    "クランレポート": "Clan Primer",
    "コンフィグ": "Config",
    "Bestiary?Edit": "",
    "Genus?Edit": "",
    "植物": "Plant",
    "怪魚": "Ichthian",
    "魔獣": "Beast",
    "ドラゴン": "Dragon",
    "怪鳥": "Avion",
    "巨人": "Giant",
    "魔法生物": "Fiend",
    "アンデッド": "Undead",
    "昆虫": "Insect",
    "軟体生物": "Amorph",
    "物質": "Construct",
    "帝国軍": "Imperial Army",
    "亜人": "Humanoid",
    "兵器": "Armament*",
    "精霊ノーマ": "Gnoma Entite",
    "雷のエレメント": "Storm Elemental",
    "精霊マルト": "Mardu Entite",
    "水のエレメント": "Water Elemental",
    "精霊サラマンド": "Salamand Entite",
    "精霊シルフス": "Sylphi Entite",
    "氷のエレメント": "Ice Elemental",
    "精霊レーシー": "Leshach Entite",
    "火のエレメント": "Fire Elemental",
    "風のエレメント": "Air Elemental",
    "土のエレメント": "Earth Elemental",
    "聖のエレメント": "Holy Elemental",
    "精霊デクアルブ": "Diakon Entite",
    "精霊ウンディーヌ": "Undin Entite",
    "精霊リョスアルブ": "Leamonde Entite",
    "闇のエレメント": "Dark Elemental",
    "モブ　ランクE": "Rank I Mark",
    "モブ　ランクD": "Rank II Mark",
    "モブ　ランクC": "Rank III Mark",
    "モブ　ランクB": "Rank IV Mark",
    "モブ　ランクA": "Rank V Mark",
    "モブ　ランクS": "Rank VI Mark",
    "ハイパーモブ": "Rank VII Mark",
    "ラストモブ": "Ultimate mark",
    "召喚獣": "Esper",
    "ボスモンスター": "Boss",
    "Class?Edit": "",
    "サボテン": "Cactoid",
    "キラーフィッシュ": "Ichthon",
    "ウルフ": "Wolf",
    "地竜": "Tyrant",
    "コッカトリス": "Cockatrice",
    "エレメント": "Elemental",
    "ダイブイーグル": "Dive Talon",
    "ダイル": "Gator",
    "キャピトゥーン": "Dreamhare",
    "タイタス": "Titantoise",
    "スレイプニル": "Sleipnir",
    "サーペント": "Serpent",
    "ベヒーモス": "Behemoth",
    "オウルベア": "Urstrix",
    "スレイヴ": "Slaven",
    "ラット": "Rat",
    "トード": "Toad",
    "モルボル": "Malboro",
    "ガーゴイル": "Gargoyle",
    "死神": "Reaper",
    "ゴースト": "Ghost",
    "スティール": "Steeling",
    "ミミック": "Mimic",
    "ゾンビ": "Zombie",
    "スケルトン": "Skeleton",
    "プリン": "Flan",
    "ボム": "Bomb",
    "ヘッドレス": "Headless",
    "マンティス": "Mantis",
    "マンドラゴラ": "Mandragora",
    "エンサ": "Yensa",
    "飛竜": "Wyvern",
    "チョコボ": "Chocobo",
    "クァール": "Coeurl",
    "ゴーレム": "Golem",
    "殻竜": "Plate Wyrm",
    "ナイトメア": "Nightmare",
    "フェイス": "Faith",
    "ガーディアン": "Guardian",
    "クリスタルバグ": "Crystalbug",
    "邪竜": "Fell Wyrm",
    "魔人": "The Gigas",
    "審判の霊樹": "Judge-Sal",
    "輪廻王": "Walker of the Wheel",
    "不浄王": "The Impure",
    "死の天使": "The Death Seraph",
    "密告者": "The Whisperer",
    "断罪の暴君": "The Condemner",
    "憤怒の霊帝": "The Wroth",
    "統制者": "Bringer of Order",
    "暗闇の雲": "The Darkening Cloud",
    "聖天使": "The High Seraph",
    "背徳の皇帝": "The Corrupt",
    "戒律王": "Keeper of Precepts",
    "炎の精霊": "Flame Spirit",
    "攻性植物": "Aggressive Vegetable",
    "巨大昆虫": "Giant Insect",
    "守護像": "Guardian Statue",
    "守護獣": "Guardian Beast",
    "中級ドラゴン": "Dragon",
    "上級地竜": "Greater Dragon",
    "怒りの精霊": "Wroth Spirit",
    "人造ドラゴン": "Manufactured Dragon",
    "獣王": "Beastlord",
    "エンシャントボム": "Ancient Bomb",
    "ダークドラゴン": "Dark Dragon",
    "ノーライフキング": "Undead Lord",
    "古代兵器": "Ancient Warmech",
    "ダルマスカ軍": "Dalmascan Military",
    "シーク族": "Seeq",
    "ウルタンエンサ族": "Urutan Exile",
    "ガリフ族": "Garif",
    "バクナムス族": "Baknamy",
    "バンガ族": "Bangaa",
    "帝国兵": "Imperial",
    "ジャッジ": "Judge",
    "上級帝国兵": "Imperial Elite",
    "帝国軍の兵器": "Imperial Armament",
    "ドクター": "Scientist",
    "Clan Primer?Edit": "",
    "モブリスト": "Hunts",
    "ハントカタログ": "Bestiary",
    "空賊の隠れ家": "Sky Pirate's Den",
    "冒険のヒント": "Traveler's Tips",
    "Clan Ranks?Edit": "",
    "グラブバッグ": "Moppet",
    "クロッグスイーパー": "Hedge Knight",
    "セーフティレイバー": "Rear Guard",
    "ゲイルレンジャーズ": "Vanguard",
    "バウンティハンターズ": "Headhunter",
    "ジャスティストルーパー": "Ward of Justice",
    "ブレイブアーミー": "Brave Companion",
    "リスクブレイカーズ": "Riskbreaker",
    "クライムアヴェンジャー": "Paragon of Justice",
    "パレスガーディアン": "High Guardian",
    "ナイツオブラウンド": "Knight of the Round",
    "アンブロシアパンテオン": "Order of Ambrosia",
    "Sky Pirate's Den Ranks?Edit": "",
    "アサルトストライカー": "Assault Striker",
    "オーバーキラー": "Blood Dancer",
    "エクスプローラー": "Cartographer",
    "ホーリーグレイル": "Collector",
    "オールマイティ": "Conqueror",
    "トップガン": "Eagle Eye",
    "ヒーローズ": "Exemplar",
    "エンジェルフォール": "Fell Angel",
    "チェイススカート": "Freshmaker",
    "アークエネミー": "High Summoner",
    "マスターハンター": "Hunter Extraordinaire",
    "トリックマスター": "Jack-of-All-Trades",
    "ロードオブザキング": "Lord of the Kings",
    "アシュラブレイド": "Master Swordsman",
    "クイックワーカー": "Master Thief",
    "ユニオンパワーズ": "Mist Walker",
    "リッチユーザー": "Plunderer",
    "ライオットパフォーマー": "Premier Prestidigitator",
    "ダブルディーラー": "Privateer",
    "グリーミングセイヴィア": "Radiant Savior",
    "レコードホルダー": "Record Breaker",
    "ルーンコマンダー": "Runeweaver",
    "ブックメーカー": "Scrivener",
    "シューティングスター": "Sharpshooter",
    "マジカルシューター": "Spellsinger",
    "ハイローラー": "Spendthrift",
    "カトゥエネイター": "The Unrelenting",
    "イヴァリースウォーカー": "Wayfarer",
    "ブラッディドラゴン": "Wyrmslayer",
    "ゾディアックブレイブ": "Zodiac Knight",
    "Locations?Edit": "",
    "ナルビナ城塞": "Nalbina Fortress",
    "ラバナスタ・ダウンタウン": "Lowtown",
    "王都ラバナスタ": "Rabanastre",
    "東ダルマスカ砂漠": "Dalmasca Estersand",
    "ギーザ草原": "Giza Plains",
    "ガラムサイズ水路": "Garamsythe Waterway",
    "西ダルマスカ砂漠": "Dalmasca Westersand",
    "ラバナスタ王宮": "Royal Palace of Rabanastre",
    "ナルビナ城塞地下牢": "Nalbina Dungeons",
    "バルハイム地下道": "Barheim Passage",
    "飛空艇定期便": "Skyferry",
    "ナルビナ城塞市街地": "Nalbina Market",
    "空中都市ビュエルバ": "Skycity of Bhujerba",
    "ルース魔石鉱": "Lhusu Mines",
    "戦艦リヴァイアサン": "Dreadnought?Leviathan",
    "大砂海オグル・エンサ": "Ogir-Yensa Sandsea",
    "大砂海ナム・エンサ": "Nam-Yensa Sandsea",
    "レイスウォール王墓": "Tomb of Raithwall",
    "ゼルテニアン洞窟": "Zertinan Caverns",
    "軽巡洋艦シヴァ": "Light Cruiser Shiva",
    "オズモーネ平原": "Ozmone Plain",
    "ガリフの地ジャハラ": "Jahara, Land of the Garif",
    "ゴルモア大森林": "Golmore Jungle",
    "エルトの里": "Eruyt Village",
    "ヘネ魔石鉱": "Henne Mines",
    "パラミナ大峡谷": "Paramina Rift",
    "神都ブルオミシェイス": "Mt Bur-Omisace",
    "ミリアム遺跡": "Stilshrine of Miriam",
    "モスフォーラ山地": "Mosphoran Highwaste",
    "サリカ樹林": "Salikawood",
    "フォーン海岸": "Phon Coast",
    "ツィッタ大草原": "Tchita Uplands",
    "ソーヘン地下宮殿": "Sochen Cave Palace",
    "アルケイディス旧市街": "Old Archades",
    "帝都アルケイディス": "Archades",
    "ドラクロア研究所": "Draklor Laboratory",
    "港町バーフォンハイム": "Balfonheim Port",
    "セロビ台地": "Cerobi Steppe",
    "幻妖の森": "The Feywood",
    "古代都市ギルヴェガン": "Giruvegan",
    "クリスタル・グランデ": "Great Crystal",
    "リドルアナ大瀑布": "The Ridorana Cataract",
    "大灯台": "The Pharos",
    "下層": "First Ascent",
    "中層": "Lower Apartments",
    "上層": "Upper Apartments",
    "地下層": "Subterra",
    "ナブレウス湿原": "Nabreus Deadlands",
    "死都ナブディス": "Necrohol of Nabudis",
    "空中要塞バハムート": "Sky Fortress?Bahamut",
    "Sub-locations?Edit": "",
    "Nalbina Fortress?Edit": "",
    "空中庭園": "Aerial Gardens",
    "内郭": "Inner Ward",
    "最上階": "The Highhall",
    "Rabanastre?Edit": "",
    "市街地東部": "East End",
    "外門前広場": "Southern Plaza",
    "東門": "Eastgate",
    "市街地北部": "North End",
    "市街地西部 ムスル・バザー": "Muthru Bazaar",
    "南部": "Southgate",
    "西部": "Westgate",
    "Lowtown?Edit": "",
    "ダウンタウン北部": "North Sprawl",
    "ダウンタウン南部": "South Sprawl",
    "Dalmasca Estersand?Edit": "",
    "砂段の丘": "The Stepping",
    "小キャンプ": "Outpost",
    "砂漠の迷宮": "Yardang Labyrinth",
    "砂原の天板": "Sand-Swept Naze",
    "地下道出入口": "Passage Entrance",
    "ネブラ河の岸辺": "Banks of the Nebra",
    "砂風止む地": "Murmuring Defile",
    "ネブラ河沿いの集落南側": "South Bank Village",
    "ネブラ河沿いの集落北側": "North Bank Village",
    "ヨーマ大砂丘": "The Yoma",
    "断裂の砂地": "Broken Sands",
    "Giza Plains?Edit": "",
    "王都への街道": "Throne Road",
    "遊牧民の集落": "Nomad Village",
    "ギーザス川沿岸北側": "Gizas North Bank",
    "ギーザス川沿岸南側": "Gizas South Bank",
    "幼き水晶のほとり": "Crystal Glade",
    "戦士の河": "Warrior's Wash",
    "トーム丘陵": "Toam Hills",
    "星ふり原": "Starfall Field",
    "巨獣の足跡": "Tracks of the Beast",
    "Dalmasca Westersand?Edit": "",
    "ガルテア丘陵": "Galtea Downs",
    "中央断層": "The Midfault",
    "陽炎立つ地平": "Shimmering Horizons",
    "風紋の地": "Windrace Dunes",
    "西境界壁": "The Western Divide",
    "砂漠の回廊": "Corridor of Sand",
    "竜のねぐら": "Wyrm's Nest",
    "Garamsythe Waterway?Edit": "",
    "最終処理区画": "Overflow Cloaca",
    "中央補助階段": "Central Spur Stairs",
    "北部取水廊": "Northern Sluiceway",
    "北部補助水路": "North Spur Sluiceway",
    "東側補助階段": "East Spur Stairs",
    "東部通水制御区画": "East Waterway Control",
    "第11主水路": "No. 11 Channel",
    "東部水量調整区": "East Sluice Control",
    "南部取水廊": "Southern Sluiceway",
    "西部水量調整区": "West Sluice Control",
    "第10主水路": "No. 10 Channel",
    "中央制御区画": "Central Waterway Control",
    "第1処理区": "No. 1 Cloaca",
    "第3処理区補助水路": "No. 3 Cloaca Spur",
    "第4処理区補助水路": "No. 4 Cloaca Spur",
    "Royal Palace of Rabanastre?Edit": "",
    "地下倉庫準備室": "Cellar Stores",
    "地下倉庫": "Cellars",
    "大広間地下": "Lower Halls",
    "秘められた路": "Secret Passage",
    "庭園保全階段": "The Garden Stairs",
    "Nalbina Dungeon?Edit": "",
    "地下雑居房": "Stockade",
    "闘技場": "Arena",
    "地下独居房入口": "The Confiscatory",
    "厳重警戒区域": "The Black Watch",
    "Barheim Passage?Edit": "",
    "配電設備区画": "The Lightworks",
    "第29作業区画": "Op Sector 29",
    "大坑道東部": "Great Eastern Passage",
    "第36作業区画": "Op Sector 36",
    "第3特別作業区": "Special Op Sector 3",
    "第37作業区画": "Op Sector 37",
    "南北連結路": "North-South Junction",
    "大坑道中央交差区": "Great Central Passage",
    "ゼバイア大空洞": "The Zeviah Subterrane",
    "第4ターミナル接続路": "Terminus No. 4 Adjunct",
    "第4ターミナルステーション": "Terminus No. 4",
    "第5特別作業区": "Special Op Sector 5",
    "東西バイパス": "East-West Bypass",
    "ゼバイア連結橋": "The Zeviah Span",
    "西部新坑道区": "West Annex",
    "第7ターミナル接続路": "Terminus No. 7 Adjunct",
    "第7ターミナルステーション": "Terminus No. 7",
    "Skyferry?Edit": "",
    "展望ロビー": "Observation Parlour",
    "スカイ・ラウンジ": "Sky Saloon",
    "フロート・デッキ": "Air Deck",
    "Nalbina Market?Edit": "",
    "外郭西広場": "West Ward",
    "ジャジム・バザー": "Jajim Bazaar",
    "西郭門前": "West Barbican",
    "Bhujerba?Edit": "",
    "トラヴィカ大通り": "Travica Way",
    "採掘作業員居住区": "Miners' End",
    "採掘場前小広場": "Lhusu Square",
    "カフ空中テラス": "Kaff Terrace",
    "浮き雲通り": "Cloudborne Row",
    "クス空中広場": "Khus Skygrounds",
    "Lhusu Mines?Edit": "",
    "坑道入口": "Shaft Entry",
    "オルタム橋": "Oltam Span",
    "第1運送路": "Transitway 1",
    "スーニア平行橋": "Shunia Twinspan",
    "第2鉱区採掘場": "Site 2",
    "第3鉱区採掘場": "Site 3",
    "第2運送路": "Transitway 2",
    "タッシェ橋": "Tasche Span",
    "第9鉱区採掘場": "Site 9",
    "第11鉱区採掘場": "Site 11",
    "ラッシェ橋": "Lasche Span",
    "第5鉱区採掘場": "Site 5",
    "第6鉱区南採掘場": "Site 6 South",
    "第6鉱区北採掘場": "Site 6 North",
    "作業準備区": "Staging Area",
    "第7鉱区採掘場": "Site 7",
    "Dreadnought Leviathan?Edit": "",
    "左翼発着ポート": "Port Launch",
    "中層西ブロック": "Port Section",
    "大型コンテナ倉庫": "Large Freight Stores",
    "中層東ブロック": "Starboard Section",
    "サブコントロールルーム": "Sub-control Room",
    "戦闘艇用ドック通路": "Airship Berth Access",
    "下層中央ブロック": "Central Brig Access",
    "第1営倉": "Brig No. 1",
    "Ogir-Yensa Sandsea?Edit": "",
    "第1工場東側タンク": "Platform 1 - East Tanks",
    "第1石油工場": "Platform 1 - Refinery",
    "東ジャンクション": "East Junction",
    "大型タンク基地": "Primary Tank Complex",
    "中央ジャンクション": "Central Junction",
    "第2石油工場": "Platform 2 - Refinery",
    "第1工場南側タンク": "Platform 1 - South Tanks",
    "南側タンクアプローチ": "South Tank Approach",
    "エンサ境界トンネル": "Yensa Border Tunnel",
    "Nam-Yensa Sandsea?Edit": "",
    "砂魚たちのみぎわ": "The Sandscale Bank",
    "ウルタン・エンサの海": "The Urutan-Yensa Sea",
    "風化する岸辺": "Withering Shores",
    "砂を読む丘": "Augur Hill",
    "黄砂のたどりつく地": "Yellow Sands",
    "女王の治める砂原": "Demesne of the Sandqueen",
    "ぬくもりの消える路": "Trail of Fading Warmth",
    "熱風の下りる高台": "Simoon Bluff",
    "Tomb of Raithwall?Edit": "",
    "死者の谷": "Valley of the Dead",
    "攻壁の間": "Hall of the Destroyer",
    "守壁の間": "Hall of the Sentinel",
    "大通廊": "Royal Passage",
    "北翼の通廊": "Northfall Passage",
    "南翼の通廊": "Southfall Passage",
    "火炎の回廊": "Cloister of Flame",
    "暁天の間": "Chamber of First Light",
    "Zertinan Caverns?Edit": "",
    "異端を誘う岩窟": "Invitation to Heresy",
    "砂落ちる間": "Sandfalls",
    "砂時計の谷": "Hourglass Basin",
    "暗きを愛でる路": "Halls of Ardent Darkness",
    "海の止まり": "The Undershore",
    "アスローズ大流砂": "Athroza Quicksands",
    "バラムカ断層": "The Balamka Fault",
    "ふりそそぐ空": "Drybeam Cavern",
    "岸壁の回廊": "Darkened Wharf",
    "地の森": "Canopy of Clay",
    "Light Cruiser Shiva?Edit": "",
    "Ozmone Plain?Edit": "",
    "翼散る草地": "Field of Fallen Wings",
    "ダガン平地": "Dagan Flats",
    "大地のらせん": "The Switchback",
    "ハウロ緑地": "Haulo Greens",
    "緑なす蛇": "The Greensnake",
    "風なびく草原": "Field of Light Winds",
    "日差し落ちる小道": "Sunlit Path",
    "ひびわれ谷": "The Shred",
    "Jahara, Land of the Garif?Edit": "",
    "ソゴト川のほとり": "Banks of the Sogoht",
    "やすらぎの大地": "Lull of the Land",
    "古き者たちの丘": "The Elderknoll",
    "Golmore Jungle?Edit": "",
    "光閉ざされし路": "Paths of Chained Light",
    "針を狂わせる路": "The Needlebrake",
    "ささやく木々の路": "Whisperleaf Way",
    "先を見通す広場": "The Parting Glade",
    "眠れる大樹の広場": "Dell of the Dreamer",
    "枝葉の分かれる路": "The Branchway",
    "緑に沈む路": "The Greenswathe",
    "葉ずれのしみる路": "The Rustling Chapel",
    "Eruyt Village?Edit": "",
    "森をうやまう路": "Road of Verdant Praise",
    "精霊の住む大樹": "The Spiritwood",
    "導きの宮": "Fane of the Path",
    "Henne Mines?Edit": "",
    "北通用口": "North Entrance",
    "坑口分岐点A": "Pithead Junction A",
    "第1期坑道": "Phase 1 Shift",
    "第1期採掘現場": "Phase 1 Dig",
    "区間連結ラインA": "Crossover A",
    "区間連結ラインB": "Crossover B",
    "坑口分岐点B": "Pithead Junction B",
    "作業準備坑": "Staging Shaft",
    "分別作業場": "Ore Separation",
    "第2期採掘現場": "Phase 2 Dig",
    "区間連結ラインC": "Crossover C",
    "坑口分岐点C": "Pithead Junction C",
    "第2期坑道": "Phase 2 Shaft",
    "特殊採掘坑": "Special Charter Shaft",
    "特殊作業坑": "Special Charter Dig",
    "Paramina Rift?Edit": "",
    "色失う谷間": "Fading Vale",
    "銀流の始まり": "Head of the Silverflow",
    "凍りつく歩み": "Freezing Gorge",
    "氷結するせせらぎ": "Frozen Brook",
    "風花散る小道": "Path of the Firstfall",
    "氷竜の骨": "Spine of the Icewyrm",
    "銀流の果て": "Silverflow's End",
    "カーリダイン大氷河": "Karydine Glacier",
    "解けることなき流れ": "Icebound Flow",
    "Mt Bur-Omisace?Edit": "",
    "白砂の小路": "Sand-strewn Pass",
    "神殿へ続く道": "Temple Approach",
    "神殿境内": "Temple Grounds",
    "光明の間": "Hall of the Light",
    "Stilshrine of Miriam?Edit": "",
    "高風の回廊": "Walk of Sky",
    "英明の回廊": "Walk of Mind",
    "具眼の守護": "Ward of Measure",
    "対面の守護": "Ward of Velitation",
    "27-5 破幻の歩廊": "Walk of Torn Illusion",
    "黙示の回廊": "Walk of Revelation",
    "剣王の守護": "Ward of the Sword-King",
    "離別の歩廊": "Cold Distance",
    "遠謀の回廊": "Walk of Prescience",
    "条理の回廊": "Walk of Reason",
    "鋼鉄の守護": "Ward of Steel",
    "修練の広間": "Hall of Worth",
    "覇者の間": "Vault of the Champion",
    "秘する神の御所": "Throne of Veiled Gods",
    "Mosphoran Highwaste?Edit": "",
    "南の山すそ": "Southern Skirts",
    "頂きを望む山道": "Summit Path",
    "天空へ続く路": "Empyrean Way",
    "灰白のひさし": "Rays of Ashen Light",
    "水音の伝わる処": "Babbling Vale",
    "岩板のそびえる路": "Trail of Sky-flung Stone",
    "北の山すそ": "Northern Skirts",
    "やませおろす橋": "Halny Crossing",
    "空の果てを知る尾根": "Skyreach Ridge",
    "蒼き天辺": "Empyrean Seat",
    "Salikawood?Edit": "",
    "きざしの見える路": "The Omen-Spur",
    "時を刻む路": "Path of Hours",
    "巨木に囲まれた路": "Trunkwall Road",
    "別離の路": "Diverging Way",
    "樹々の狭間": "Living Chasm",
    "木もれ日の路": "Sun-dappled Path",
    "朽ちた木々の庭": "Garden of Decay",
    "いやしの響く路": "Quietened Trace",
    "古き集いの庭": "Grand Bower",
    "年輪を重ねる路": "Corridor of Ages",
    "白きまだらの路": "Piebald Path",
    "Phon Coast?Edit": "",
    "カウクラ小路": "Kaukula Pass",
    "リシタ海岸": "The Reseta Strand",
    "マウレア海岸": "The Mauleia Strand",
    "ポラポラ砂地": "Pora-Pora Sands",
    "ウアフカ岬": "Cape Uahuk",
    "ティアラウヌ岬": "Cape Tialan",
    "ハカウイの岸辺": "The Hakawea Shore",
    "ハンターズ・キャンプ": "Hunters' Camp",
    "ヴァドゥ海岸": "The Vaddu Strand",
    "カイマの丘": "Caima Hills",
    "リマタラの丘": "Limatra Hills",
    "ラバの小路": "Rava's Pass",
    "Tchita Uplands?Edit": "",
    "古き想いの眠る地": "Realm of the Elder Dream",
    "天に続いていた道": "The Skytrail",
    "決断の途": "The Chosen Path",
    "オリフザックの丘": "Oliphzak Rise",
    "名もなき泉": "The Nameless Spring",
    "終焉と旅立ちの庭": "Garden of Life's Circle",
    "全てを見通す地": "The Highlands",
    "三界交わる草原": "Fields of Eternity",
    "裂けた大地": "Sundered Earth",
    "失われた街道": "The Lost Way",
    "ワズクフ丘陵": "Uazcuff Hills",
    "昏き道": "The Shaded Path",
    "Sochen Cave Palace?Edit": "",
    "迷いを捨てる路": "Doubt Abandoned",
    "明るき闇と対する広間": "Hall of Lambent Darkness",
    "修道者が息をつく場所": "The Acolyte's Burden",
    "自らを見出す路": "Mirror of the Soul",
    "時の水洞": "Falls of Time",
    "定めを受け入れる路": "Destiny's March",
    "暗き光と対する広間": "Hall of Shadowlight",
    "誘惑を振りほどく路": "Temptation Eluded",
    "選ばれし者の部屋": "Chamber of the Chosen",
    "天をあおぐ部屋": "Skybent Chamber",
    "怒れる神と対する広間": "Hall of the Wroth God",
    "Old Archades?Edit": "",
    "むかい風の路地": "Alley of Low Whispers",
    "すきま風の路地": "Alley of Muted Sighs",
    "Imperial City of Archades?Edit": "",
    "トラント区": "Trant",
    "リーアナ区": "Rienna",
    "モールベリ区": "Molberry",
    "ニルバス区": "Nilbasse",
    "ゼノーブル区": "Tsenoble",
    "エア・アーケード": "Grand Arcade",
    "高層テラス": "Highgarden Terrace",
    "Draklor Laboratory?Edit": "",
    "第66階層": "66th Floor",
    "第67階層": "67th Floor",
    "第68階層": "68th Floor",
    "第70階層": "70th Floor",
    "エネルギー送配施設": "Energy Transitarium",
    "Balfonheim Port?Edit": "",
    "サッシオ通り": "Saccio Lane",
    "船乗りの広場": "Quayside Court",
    "水路通り": "Canal Lane",
    "ガラリナ市場": "Gallerina Marketplace",
    "海風通り": "Sea Breeze Lane",
    "シバーネ波止場": "Chivany Breakwater",
    "Cerobi Steppe?Edit": "",
    "南リィーヴィル丘陵": "South Liavell Hills",
    "北リーヴィル丘陵": "North Liavell Hills",
    "河岸段丘": "The Terraced Bank",
    "街道の休息所": "Journey's Rest",
    "フェディック川": "Feddik River",
    "北部段丘": "The Northsward",
    "交差ヶ原": "Crossfield",
    "エルアニス旧街道": "Old Elanise Road",
    "Feywood?Edit": "",
    "ゆがみうつろう路": "Walk of Flitting Rifts",
    "現を惑わす路": "Walk of Stolen Truths",
    "影の舞う路": "Walk of Dancing Shadow",
    "古の終わる処": "Antiquity's End",
    "においたつ花の庭": "Redolent Glade",
    "白魔の愛でし路": "White Magick's Embrace",
    "英知の氷原": "Ice Field of Clearsight",
    "思の最果て": "The Edge of Reason",
    "Giruvegan?Edit": "",
    "地の門": "Gate of Earth",
    "水の門": "Gate of Water",
    "水層都市トリマーラ": "The Trimahla Water-Steps",
    "水層都市アウダ": "The Aadha Water-Steps",
    "水層都市ハルミカ": "The Haalmikah Water-Steps",
    "火の門": "Gate of Fire",
    "風の門": "Gate of Wind",
    "Great Crystal?Edit": "",
    "ア・グランド・シフト": "A Prama Vikaari",
    "カボニフ・ザイレム・ウェサ": "Kabonii Jilaam Pratii'vaa",
    "カボニフ・ザイレム・サ": "Kabonii Jilaam Avaa",
    "ダ・シフト・ベルム": "Dha Vikaari Bhrum",
    "ア・シフト・カボニフ": "A Vikaari Kabonii",
    "セット・キャンサー": "Sthaana Cancer",
    "ベルム・ピス・サ": "Bhrum Pis Avaa",
    "ベルム・ピス・ウェ": "Bhrum Pis Pratii",
    "ダ・シフト・トリアック": "Dha Vikaari Trahk",
    "ア・シフト・ベルム": "A Vikaari Bhrum",
    "トリアック・ザイレム・イノ": "Trahk Jilaam Praa'dii",
    "セット・アリエス": "Sthaana Aries",
    "トリアック・ピス・イ": "Trahk Pis Praa",
    "セット・パイシーズ": "Sthaana Pisces",
    "ダ・シフト・ジュラ": "Dha Vikaari Jula",
    "クリスタル・コア": "Crystal Core",
    "セット・スコーピオ": "Sthaana Scorpio",
    "ア・シフト・デボン": "A Vikaari Dhebon",
    "ダ・シフト・カボニフ": "Dha Vikaari Kabonii",
    "ア・シフト・カンブル・ラ": "A Vikaari Kanbhru Ra",
    "デボン・ザイレム・イノ": "Dhebon Jilaam Praa'dii",
    "デボン・ザイレム・ウェノ": "Dhebon Jilaam Pratii'dii",
    "セット・サジタリウス": "Sthaana Sagittarius",
    "ア・シフト・シルル・イ": "A Vikaari Sirhru Praa",
    "ア・シフト・シルル・ウェ": "A Vikaari Sirhru Pratii",
    "ダ・シフト・デボン・イ": "Dha Vikaari Dhebon Praa",
    "シルル・フロウェン・イ": "Sirhru Phullam Praa",
    "シルル・フロウェン・イサ": "Sirhru Phullam Praa'vaa",
    "セット・ジェミニ": "Sthaana Gemini",
    "シルル・ザイレム・イノ": "Sirhru Jilaam Praa'dii",
    "シルル・ザイレム・イ": "Sirhru Jilaam Praa",
    "シルル・ザイレム・イサ": "Sirhru Jilaam Praa'vaa",
    "シルル・ピス・イ": "Sirhru Pis Praa",
    "ダ・シフト・デボン・ウェ": "Dha Vikaari Dhebon Pratii",
    "セット・レオ": "Sthaana Leo",
    "シルル・フロウェン・ウェサ": "Sirhru Phullam Pratii'vaa",
    "シルル・フロウェン・ノウェ": "Sirhru Phullam Udiipratii",
    "シルル・ザイレム・ウェノ": "Sirhru Jilaam Pratii'dii",
    "シルル・ザイレム・ウェ": "Sirhru Jilaam Pratii",
    "シルル・ザイレム・ウェサ": "Sirhru Jilaam Pratii'vaa",
    "シルル・ピス・ウェ": "Sirhru Pis Pratii",
    "シルル・ピス・サ": "Sirhru Pis Avaa",
    "シルル・ザイレム・サイ": "Sirhru Jilaam Avaapratii",
    "シルル・ザイレム・サウェ": "Sirhru Jilaam Avaapraa",
    "ア・シフト・オルドビ": "A Vikaari Uldobi",
    "ダ・シフト・シルル": "Dha Vikaari Sirhru",
    "オルドビ・ザイレム・イノ": "Uldobi Jilaam Praa'dii",
    "セット・リーブラ": "Sthaana Libra",
    "オルドビ・ザイレム・イサ": "Uldobi Jilaam Praa'vaa",
    "オルドビ・ザイレム・イ": "Uldobi Jilaam Praa",
    "セット・カプリコーン": "Sthaana Capricorn",
    "オルドビ・フロウェン・ノイ": "Uldobi Phullam Udiipraa",
    "セット・ヴァルゴ": "Sthaana Virgo",
    "オルドビ・ザイレム・ウェサ": "Uldobi Jilaam Pratii'vaa",
    "オルドビ・ザイレム・サ": "Uldobi Jilaam Avaa",
    "ア・シフト・カンブル": "A Vikaari Kanbhru",
    "ダ・シフト・オルドビ": "Dha Vikaari Uldobi",
    "カンブル・ピス": "Kanbhru Pis",
    "クリスタル・ピーク": "Crystal Peak",
    "ダ・シフト・デボン・ラ": "Dha Vikaari Dhebon Ra",
    "セット・アクエリアス": "Sthaana Aquarius",
    "オルドビ・フロウェン・イサ": "Uldobi Phullam Praa'vaa",
    "セット・タウロス": "Sthaana Taurus",
    "オルドビ・ザイレム・ウェ": "Uldobi Jilaam Pratii",
    "オルドビ・フロウェン・ウェサ": "Uldobi Phullam Pratii'vaa",
    "オルドビ・フロウェン・ウェ": "Uldobi Phullam Pratii",
    "オルドビ・フロウェン・ウェノ": "Uldobi Phullam Pratii'dii",
    "ダ・シフト・シルル・シ": "Dha Vikaari Sirhru Si",
    "ア・シフト・オルドビ・シ": "A Vikaari Uldobi Si",
    "ダ・シフト・デボン・シ": "Dha Vikaari Dhebon Si",
    "ア・シフト・シルル・シ": "A Vikaari Sirhu Si",
    "デボン・ザイレム・サ": "Dhebon Jilaam Avaa",
    "Ridorana Cataract?Edit": "",
    "先人の記憶に遺されし路": "Footfalls of the Past",
    "はるかなる時の庭": "Echoes from Time's Garden",
    "コロセウム": "Colosseum",
    "遠き日の都": "City of Other Days",
    "いのりを秘めて歩いた路": "Path of Hidden Blessing",
    "Pharos?Edit": "",
    "First Ascent": "",
    "かわき満たす広場": "They Who Thirst Not",
    "始原の層 内郭": "The Wellspring",
    "始原の層 外郭": "Wellspring Labyrinth",
    "黒き石室": "Blackrock Vault",
    "異なる風吹く迷いの砂丘": "Dunes of Profaning Wind",
    "始原の旋回廊1": "Wellspring Ravel - 1st Flight",
    "始原の旋回廊2": "Wellspring Ravel - 2nd Flight",
    "始原の旋回廊3": "Wellspring Ravel - 3rd Flight",
    "始原の旋回廊4": "Wellspring Ravel - 4th Flight",
    "至次の狭間": "Horizon's Break",
    "至次の境域": "Horizon's Cusp",
    "異なる風吹く水盤の地": "Marsh of Profaning Wind",
    "Second Ascent": "",
    "ささげし狭間": "The Reach",
    "封殺の層": "Station of Banishment",
    "受難の層": "Station of Suffering",
    "幻惑の層": "Station of Ascension",
    "封滅の狭間": "Reach of the Damned",
    "験真の封域": "The Bounds of Truth",
    "異なる風吹く白き闘場": "Cleft of Profaning Wind",
    "封隠の狭間": "Reach of the Occult",
    "Third Ascent": "",
    "至頂の旋回廊1": "Spire Ravel - 1st Flight",
    "至頂の旋回廊2": "Spire Ravel - 2nd Flight",
    "至天の戦域（上層）": "Heaven's Challenge",
    "至天の旋回廊": "Empyrean Road",
    "天陽の界域": "Womb of the Sun-cryst",
    "Subterra": "",
    "暗影の層 内郭": "Penumbra - Interior",
    "暗影の層 北外郭": "Penumbra - North",
    "暗影の層 南外郭": "Penumbra - South",
    "闇昏の層 内郭": "Umbra - Interior",
    "闇昏の層 北外郭": "Umbra - North",
    "闇昏の層 南外郭": "Umbra - South",
    "陰裏の層 内郭": "Abyssal - Interior",
    "陰裏の層 北外郭": "Abyssal - North",
    "陰裏の層 南外郭": "Abyssal - South",
    "至天の戦域（地下層）": "Heaven's Challenge",
    "Nabreus Deadlands?Edit": "",
    "緑岩の地": "Greencrag",
    "声を失った路": "The Muted Scarp",
    "なげきよどむ地": "Vale of Lingering Sorrow",
    "陽を探す路": "Hope's Reach",
    "追憶の地": "Echoes of the Past",
    "まどろみへ誘う平原": "The Slumbermead",
    "霧のさざめく路": "The Fog Mutters",
    "永遠を見下ろす高台": "Overlooking Eternity",
    "はげましを受けた地": "Succour Midst Sorrow",
    "命消えし水辺": "Lifeless Strand",
    "滅びし王家の広場": "Field of the Fallen Lord",
    "Necrohol of Nabudis?Edit": "",
    "力宿る回廊": "Hall of Slumbering Might",
    "白き約束の回廊": "Hall of the Ivory Covenant",
    "ゆらぎなき理の間": "Cloister of Reason",
    "気高き者たちの間": "Cloister of the Highborn",
    "美しき調べの間": "Cloister of Distant Song",
    "大いなるなぐさめの間": "Cloister of Solace",
    "光満ちる回廊": "Hall of Effulgent Light",
    "勇なる望みの間": "The Crucible",
    "Sky Fortress Bahamut?Edit": "",
    "ゲートルーム（東）": "Antechamber",
    "中央エリア外郭通路（北東）": "Periphery",
    "ゲートルーム（北）": "Antechamber",
    "中央エリア外郭通路（北西）": "Periphery",
    "ゲートルーム（西）": "Antechamber",
    "中央エリア外郭通路（南西）": "Periphery",
    "ゲートルーム（南）": "Antechamber",
    "45-8 中央エリア外郭通路（南東）": "Periphery",
    "中央エリア内郭通路": "Catwalk",
    "中央リフト": "Central Lift",
    "セントラル・シャフト": "Central Shaft",
    "主砲防護フレーム": "Cannon Superstructure",
    "Licenses?Edit": "",
    "ＨＰ＋５０": "+50 HP",
    "ＨＰ＋１００": "+100 HP",
    "ＨＰ＋１５０": "+150 HP",
    "ＨＰ＋２００": "+200 HP",
    "ＨＰ＋５００": "+500 HP",
    "力強化": "Battle Lore",
    "魔力強化": "Magick Lore",
    "ＨＰ満タン攻撃力ＵＰ": "Full-HP ATK+",
    "ＨＰ満タン魔力ＵＰ": "Serenity",
    "瀕死攻撃力ＵＰ": "Low-HP ATK+",
    "瀕死魔力ＵＰ": "Low-HP Mag+",
    "瀕死防御力ＵＰ": "Low-HP Def+",
    "格闘": "Brawl",
    "盾回避率ＵＰ": "Shield Block",
    "加ダメージチャージ": "Inquisitor",
    "魔法チャージ": "Warmage",
    "ターミネートチャージ": "Headsman",
    "被ダメージチャージ": "Martyr",
    "行動時間短縮": "Swiftness",
    "消費ＭＰカット": "Channeling",
    "有効ステータス時間延長": "Status+",
    "ポーションの知識１": "Potion Lore 1",
    "エーテルの知識１": "Ether Lore 1",
    "万能薬の知識１": "Remedy Lore 1",
    "フェニックス効果ＵＰ": "Phoenix Lore",
    "ガンビットプラス": "Gambit Slot",
    "アクセサリ１": "Accessories 1",
    "リボン装備": "Ribbon",
    "魔装備１": "Mystic Armor 1",
    "軽装備１": "Light Armor 1",
    "源氏装備": "Genji Armor",
    "重装備１": "Heavy Armor 1",
    "盾装備１": "Shields 1",
    "最強盾装備": "Zodiac Escutcheon",
    "シェルシールド": "Shell Shield",
    "呪盾装備": "Ensanguined Shield",
    "黒魔法１": "Black Magick 1",
    "緑魔法１": "Green Magick 1",
    "裏魔法１": "Arcane Magick 1",
    "白魔法１": "White Magick 1",
    "時空魔法１": "Time Magick 1",
    "ミストナック": "Quickening",
    "アルテマ": "Ultima",
    "ファムフリート": "Famfrit",
    "ベリアス": "Belias",
    "シュミハザ": "Shemhazai",
    "キュクレイン": "C?chulainn",
    "マティウス": "Mateus",
    "ゾディアーク": "Zodiark",
    "カオス": "Chaos",
    "ゼロムス": "Zeromus",
    "エクスデス": "Exodus",
    "ザルエラ": "Zalera",
    "ハシュマリム": "Hashmal",
    "アドラメレク": "Adrammelech",
    "防御破壊": "Expose",
    "無作為魔": "Shades of Black",
    "蘇生": "Revive",
    "銭投げ": "Gil Toss",
    "算術": "Numerology",
    "魔攻破壊": "Addle",
    "暗黒殺法": "Sight Unseeing",
    "アキレス": "Achilles",
    "貼付": "Stamp",
    "肉斬骨断": "Bonecrusher",
    "攻撃破壊": "Wither",
    "遠隔攻撃": "Telekinesis",
    "ライブラ": "Libra",
    "応急処置": "First Aid",
    "チャージ": "Charge",
    "時間攻撃": "Horology",
    "密猟": "Poach",
    "盗む": "Steal",
    "ＭＰＨＰ": "Infuse",
    "針千本": "1000 Needles",
    "暗黒": "Souleater",
    "歩数攻撃": "Traveler",
    "魔防破壊": "Shear",
    "勧誘": "Charm",
    "軍刀装備": "Smallswords",
    "剣装備１": "Swords 1",
    "弓装備１": "Bows 1",
    "槍装備１": "Spears 1",
    "ブラッドソード装備": "Blood Sword",
    "竜装備": "Dragon Whisker",
    "聖剣装備": "Excalibur",
    "ブレイカー装備１": "Axes & Hammers1",
    "刀装備１": "Katana 1",
    "サジタリア装備": "Sagittarius",
    "最強矛装備": "Zodiac Spear",
    "騎士剣装備１": "Greatswords 1",
    "最強剣装備": "Tournesol",
    "フェイスロッド装備": "Rod of Faith",
    "賢者の杖装備": "Staff of Magi",
    "杖装備１": "Staves 1",
    "メイス装備１": "Maces 1",
    "計算尺装備１": "Measures 1",
    "ロッド装備１": "Rods 1",
    "ハンディＢ装備１": "Hand-bombs 1",
    "忍刀装備１": "Ninja Swords 1",
    "柳生刀装備": "Yagyu Darkblade",
    "ダンジューロ装備": "Danjuro",
    "銃装備１": "Guns 1",
    "ボウガン装備１": "Crossbows 1",
    "棒装備１": "Poles 1",
    "ダガー装備１": "Daggers 1",
    "鯨装備": "Whale Whisker",
    "Zodiac?versionsEdit": "",
    "おろち柳生装備": "Yagyu Darkblade & Mesa",
    "ナガサ装備": "Shikari Nagasa & Mina",
    "Ｌボードプラス": "Second Board",
    "ライセンスボードをもうひとつ所持": "Additional License Board unlocked.",
    "Gambits?Edit": "",
    "味方1人": "Ally: Any",
    "リーダー": "Ally: party leader",
    "最もHPが低い味方": "Ally: lowest HP",
    "最も武器の強い味方": "Ally: strongest weapon",
    "最も物理防御低い味方": "Ally: lowest defense",
    "最も魔法防御低い味方": "Ally: lowest magick resist",
    "HP＜〇〇％の味方": "Ally: HP <XX%",
    "MP＜100％の味方": "Ally: MP <XX%",
    "「リジェネ」の味方": "Ally: status = Regen",
    "「浮遊」の味方": "Ally: status = Float",
    "「バブル」の味方": "Ally: status = Bubble",
    "「ストップ」の味方": "Ally: status = Stop",
    "「睡眠」の味方": "Ally: status = Sleep",
    "「混乱」の味方": "Ally: status = Confuse",
    "「逆転」の味方": "Ally: status = Reverse",
    "「スロウ」の味方": "Ally: status = Slow",
    "「おとり」の味方": "Ally: status = Lure",
    "「リフレク」の味方": "Ally: status = Reflect",
    "「狂戦士」の味方": "Ally: status = Berserk",
    "「瀕死」の味方": "Ally: status = HP Critical",
    "残り≧10コなら味方へ": "Ally: item AMT ≧ 10",
    "残り≧10コなら味方に": "",
    "「戦闘不能」の味方": "Ally: status = KO",
    "「石化」の味方": "Ally: status = Stone",
    "「石化中」の味方": "Ally: status = Petrify",
    "「死の宣告」の味方": "Ally: status = Doom",
    "「くらやみ」の味方": "Ally: status = Blind",
    "「猛毒」の味方": "Ally: status = Poison",
    "「沈黙」の味方": "Ally: status = Silence",
    "「スリップ」の味方": "Ally: status = Sap",
    "「オイル」の味方": "Ally: status = Oil",
    "「ドンアク」の味方": "Ally: status = Disable",
    "「ドンムブ」の味方": "Ally: status = Immobilize",
    "「ウイルス」の味方": "Ally: status = Disease",
    "「プロテス」の味方": "Ally: status = Protect",
    "「シェル」の味方": "Ally: status = Shell",
    "「ヘイスト」の味方": "Ally: status = Haste",
    "「ブレイブ」の味方": "Ally: status = Bravery",
    "「フェイス」の味方": "Ally: status = Faith",
    "「透明」の味方": "Ally: status = Invisible",
    "リーダーの敵": "Foe: party leader's target",
    "目の前の敵": "Foe: nearest visible",
    "敵1体": "Foe: any",
    "リーダーを狙う敵": "Foe: targeting leader",
    "自分を狙う敵": "Foe: targeting self",
    "味方を狙う敵": "Foe: targeting ally",
    "最も遠い敵": "Foe: furthest",
    "最も近い敵": "Foe: nearest",
    "最もHPが高い敵": "Foe: highest HP",
    "最もHPが低い敵": "Foe: lowest HP",
    "最もMPが高い敵": "Foe: highest MP",
    "最もMPが低い敵": "Foe: lowest MP",
    "最もHPmaxが高い敵": "Foe: highest max HP",
    "最もHPmaxが低い敵": "Foe: lowest max HP",
    "最もMPmaxが高い敵": "Foe: highest max MP",
    "最もMPmaxが低い敵": "Foe: lowest max MP",
    "最もレベルが高い敵": "Foe: highest level",
    "最もレベルが低い敵": "Foe: lowest level",
    "最も力が高い敵": "Foe: highest strength",
    "最も力が低い敵": "Foe: lowest strength",
    "最も魔力が高い敵": "Foe: highest magick power",
    "最も魔力が低い敵": "Foe: lowest magick power",
    "最もスピードが高い敵": "Foe: highest speed",
    "最もスピードが低い敵": "Foe: lowest speed",
    "最も物理防御が高い敵": "Foe: highest defense",
    "最も物理防御が低い敵": "Foe: highest magick resist",
    "HP≧〇〇の敵": "Foe: HP ≧ X",
    "HP＜〇〇の敵": "Foe: HP < XX",
    "HP＝100％の敵": "Foe: HP = 100%",
    "HP≧〇〇％の敵": "Foe: HP ≧ XX%",
    "「石化中」の敵": "Foe: status = Petrify",
    "「ストップ」の敵": "Foe: status = Stop",
    "「睡眠」の敵": "Foe: status = Sleep",
    "「混乱」の敵": "Foe: status = Confuse",
    "「死の宣告」の敵": "Foe: status = Doom",
    "「くらやみ」の敵": "Foe: status = Blind",
    "「猛毒」の敵": "Foe: status = Poison",
    "「沈黙」の敵": "Foe: status = Silence",
    "「スリップ」の敵": "Foe: status = Sap",
    "「オイル」の敵": "Foe: status = Oil",
    "「逆転」の敵": "Foe: status = Reverse",
    "「ドンアク」の敵": "Foe: status = Disable",
    "「ドンムブ」の敵": "Foe: status = Immobilize",
    "「スロウ」の敵": "Foe: status = Slow",
    "「ウイルス」の敵": "Foe: status = Disease",
    "「プロテス」の敵": "Foe: status = Protect",
    "「シェル」の敵": "Foe: status = Shell",
    "「ヘイスト」の敵": "Foe: status = Haste",
    "「ブレイブ」の敵": "Foe: status = Bravery",
    "「フェイス」の敵": "Foe: status = Faith",
    "「リフレク」の敵": "Foe: status = Reflect",
    "「リジェネ」の敵": "Foe: status = Regen",
    "「狂戦士」の敵": "Foe: status = Berserk",
    "「瀕死」の敵": "Foe: status = HP Critical",
    "「火」に弱い敵": "Foe: fire-weak",
    "「雷」に弱い敵": "Foe: lightning-weak",
    "「氷」に弱い敵": "Foe: ice-weak",
    "「土」に弱い敵": "Foe: earth-weak",
    "「水」に弱い敵": "Foe: water-weak",
    "「風」に弱い敵": "Foe: wind-weak",
    "「聖」に弱い敵": "Foe: holy-weak",
    "「闇」に弱い敵": "Foe: dark-weak",
    "「火」を吸収しない敵": "Foe: fire-vulnerable",
    "「雷」を吸収しない敵": "Foe: lightning-vulnerable",
    "「氷」を吸収しない敵": "Foe: ice-vulnerable",
    "「土」を吸収しない敵": "Foe: earth-vulnerable",
    "「水」を吸収しない敵": "Foe: water-vulnerable",
    "「風」を吸収しない敵": "Foe: wind-vulnerable",
    "「聖」を吸収しない敵": "Foe: holy-vulnerable",
    "「闇」を吸収しない敵": "Foe: dark-vulnerable",
    "アンデッドの敵": "Foe: undead",
    "飛行タイプの敵": "Foe: flying",
    "残り≧10コなら敵へ": "Foe: item AMT ≧ 10",
    "もしHP＝100％なら": "Foe: character HP=100%",
    "もし「くらやみ」なら": "Foe: character status = Blind",
    "もし「沈黙」なら": "Foe: character status = Silence",
    "もし「ブレイブ」なら": "Foe: character status = Bravery",
    "もし「フェイス」なら": "Foe: character status = Faith",
    "もし「瀕死」なら": "Foe: character status = HP Critical",
    "もしMP≧〇〇％なら": "Foe: character MP ≧ XX%",
    "もしHP≧〇〇％なら": "Foe: character HP ≧ XX%",
    "自分自身": "Self",
    "HP＜〇〇％の自分": "Self: HP < XX%",
    "MP＜〇〇％の自分": "Self: MP < XX%",
    "「瀕死」の自分": "Self: status = HP Critical",
    "「石化中」の自分": "Self: status = Petrify",
    "「死の宣告」の自分": "Self: status = Doom",
    "「くらやみ」の自分": "Self: status = Blind",
    "「猛毒」の自分": "Self: status = Poison",
    "「沈黙」の自分": "Self: status = Silence",
    "「スリップ」の自分": "Self: status = Sap",
    "「オイル」の自分": "Self: status = Oil",
    "「逆転」の自分": "Self: status = Reverse",
    "「ドンムブ」の自分": "Self: status = Immobilize",
    "「スロウ」の自分": "Self: status = Slow",
    "「ウイルス」の自分": "Self: status = Disease",
    "「おとり」の自分": "Self: status = Lure",
    "「プロテス」の自分": "Self: status = Protect",
    "「シェル」の自分": "Self: status = Shell",
    "「ヘイスト」の自分": "Self: status = Haste",
    "「ブレイブ」の自分": "Self: status = Bravery",
    "「フェイス」の自分": "Self: status = Faith",
    "「リフレク」の自分": "Self: status = Reflect",
    "「透明」の自分": "Self: status = Invisible",
    "「リジェネ」の自分": "Self: status = Regen",
    "「浮遊」の自分": "Self: status = Float",
    "「バブル」の自分": "Self: status = Bubble",
    "ゲスト": "Guest",
    "敵〇体以上で味方に": "Ally: X+ foes present",
    "集中攻撃": "Foe: targeted by ally",
    "分散攻撃": "Foe: not targeted by ally",
    "ヴァンを狙う敵": "Foe: targeting Vaan",
    "アーシェを狙う敵": "Foe: targeting Ashe",
    "フランを狙う敵": "Foe: targeting Fran",
    "バルフレアを狙う敵": "Foe: targeting Balthier",
    "バッシュを狙う敵": "Foe: targeting Basch",
    "パンネロを狙う敵": "Foe: targeting Penelo",
    "HP≧90%の敵": "Foe: HP ≧ 90%",
    "HP≧10%の敵": "Foe: HP ≧ 10%",
    "HP＜〇〇%の敵": "Foe: HP < XX%",
    "敵〇体以上で敵に": "Foe: X+ foes present",
    "味方〇人以上で敵に": "Foe: X+ allies present",
    "敵〇体以上で自分に": "Self: X+ foes present",
    "敵に狙われ中の自分": "Self: targeted by enemies",
    "味方に狙われ中の自分": "Self: targeted by allies",
    "残り≧10コなら自分に": "Self: item AMT ≧ 10",
    "Abilities?Edit": "",
    "Quickenings?Edit": "",
    "レッドスパイラル": "Red Spiral",
    "ディープハザード": "White Whorl",
    "メルトクリムゾン": "Pyroclasm",
    "略奪のコンパス": "Fires of War",
    "宿命のポルトラン": "Tides of Fate",
    "謀逆のアスペクト": "Element of Treachery",
    "乱命割殺掌": "Feral Strike",
    "強甲破点蹴": "Whip Kick",
    "咬撃氷狼波": "Shatterheart",
    "闇と暗黒の衝撃": "Fulminating Darkness",
    "紛れ無き終焉": "Ruin Impendent",
    "百鬼・烈日の破邪": "Flame Purge",
    "北斗骨砕斬": "Northswain's Glow",
    "": "Cudgel",
    "聖光爆裂斬": "Heaven's Wrath",
    "天鼓雷音稲妻斬": "Maelstrom's Bolt",
    "生殺与奪": "Intercession",
    "雲散霧消": "Evanescence",
    "山紫水明": "Resplendence",
    "融合技": "Concurrences",
    "炎のインフェルノ": "Inferno",
    "土のカタクラズム": "Cataclysm",
    "水のイラプション": "Torrent",
    "風のラプチャー": "Windburst",
    "ホワイトアウト": "Whiteout",
    "アークブラスト": "Ark Blast",
    "ルミネッセンス": "Luminescence",
    "ブラックホール": "Black Hole",
    "Augments?Edit": "",
    "Magick?Edit": "",
    "Black Magick?Edit": "",
    "ファイア": "Fire",
    "サンダー": "Thunder",
    "ブリザド": "Blizzard",
    "ウォータ （アクア）": "Water",
    "エアロ": "Aero",
    "ファイラ": "Fira",
    "サンダラ": "Thundara",
    "ブリザラ": "Blizzara",
    "バイオ": "Bio",
    "エアロガ": "Aeroga",
    "ファイガ": "Firaga",
    "サンダガ": "Thundaga",
    "ブリザガ": "Blizzaga",
    "ショック": "Shock",
    "クラウダ": "Scourge",
    "フレアー": "Flare",
    "アーダー": "Ardor?(Ardour)",
    "コラプス": "Scathe",
    "White Magick?Edit": "",
    "ケアル": "Cure",
    "ケアルラ": "Cura",
    "ケアルダ": "Curaga",
    "ケアルガ": "Curaja",
    "フルケア": "Renew",
    "レイズ": "Raise",
    "アレイズ": "Arise",
    "エスナ": "Esuna",
    "エスナガ": "Esunaga",
    "ブラナ": "Blindna",
    "ボキャル": "Vox",
    "ポイゾナ": "Poisona",
    "ストナ": "Stona",
    "リブート": "Cleanse",
    "デスペル": "Dispel",
    "デスペガ": "Dispelga",
    "リジェネ": "Regen",
    "ホーリー": "Holy",
    "Time Magick?Edit": "",
    "ヘイスト": "Haste",
    "ヘイスガ": "Hastega",
    "スロウ": "Slow",
    "スロウガ": "Slowga",
    "ドンムブ": "Immobilize",
    "ドンアク": "Disable",
    "ストップ": "Stop",
    "リフレク": "Reflect",
    "リフレガ": "Reflectga",
    "レビテガ": "Float",
    "ブレイク": "Break",
    "カウント": "Countdown",
    "バランス": "Balance",
    "バヒール": "Bleed",
    "デジョン": "Warp",
    "Green Magick?Edit": "",
    "プロテス": "Protect",
    "プロテガ": "Protectga",
    "シェル": "Shell",
    "シェルガ": "Shellga",
    "ブレイブ": "Bravery",
    "ブライン": "Blind",
    "ブライガ": "Blindga",
    "サイレス": "Silence",
    "サイレガ": "Silencega",
    "スリプル": "Sleep",
    "スリプガ": "Sleepga",
    "ポイズン": "Poison",
    "タクシク": "Toxify",
    "オイル": "Oil",
    "Arcane Magick?Edit": "",
    "ダーク": "Dark",
    "ダーラ": "Darkra",
    "ダーガ": "Darkga",
    "グラビデ": "Gravity",
    "グラビガ": "Graviga",
    "リバース": "Reverse",
    "バーサク": "Berserk",
    "コンフュ": "Confuse",
    "デコイ": "Decoy",
    "デス": "Death",
    "バニシュ": "Vanish",
    "バニシガ": "Vanishga",
    "バブル": "Bubble",
    "ドレイン": "Drain",
    "アスピル": "Syphon",
    "Technicks?Edit": "",
    "応急処置 （応急手当）": "First Aid",
    "Espers?Edit": "",
    "魔人ベリアス": "Belias, the Gigas",
    "背徳の皇帝マティウス": "Mateus, the Corrupt",
    "憤怒の霊帝アドラメレク": "Adrammelech, the Wroth",
    "死の天使ザルエラ": "Zalera, the Death Seraph",
    "密告者シュミハザ": "Shemhazai, the Whisperer",
    "統制者ハシュマリム": "Hashmal, Bringer of Order",
    "不浄王キュクレイン": "C?chulainn, the Impure",
    "断罪の暴君ゼロムス": "Zeromus, the Condemner",
    "審判の霊樹エクスデス": "Exodus, the Judge-Sal",
    "暗闇の雲ファムフリート": "Famfrit, the Darkening Cloud",
    "輪廻王カオス": "Chaos, Walker of the Wheel",
    "聖天使アルテマ": "Ultima, the High Seraph",
    "戒律王ゾディアーク": "Zodiark, Keeper of Precepts",
    "Esper Attacks?Edit": "",
    "ペインフレア": "Painflare",
    "地獄の火炎": "Hellfire",
    "凍天撃": "Flash-Freeze",
    "凍てつく波動": "Frostwave",
    "閃光咆": "Flash Arc",
    "裁きの雷": "Judgment Bolt",
    "キル": "Kill",
    "ディバインデス": "Condemnation",
    "充填撃": "Devour Soul",
    "ソウルエミット": "Soul Purge",
    "ロックユー": "Roxxor",
    "大地の怒り": "Gaia's Wrath",
    "蟲毒瘴": "Malaise",
    "ベノムバイト": "Blight",
    "黒滅丸": "Gravity Well",
    "ビッグバン": "Big Bang",
    "コメット": "Comet",
    "メテオ": "Meteor",
    "蒼の砲撃": "Briny Cannonade",
    "大海嘯": "Tsunami",
    "トルネド": "Whirlwind",
    "ハリケーン": "Tornado",
    "破壊": "Redemption",
    "完全アルテマ": "Eschaton",
    "バニッシュレイ": "Banish Ray",
    "ラストエクリプス (終のエクリプス)": "Final Eclipse",
    "Equipment?Edit": "",
    "Weapons?Edit": "",
    "片手剣": "Sword",
    "片手ダガー": "Dagger",
    "片手斧": "Axe",
    "片手ハンマー": "Hammer",
    "片手メイス": "Mace",
    "片手計算尺": "Measure",
    "両手剣": "Greatsword",
    "両手刀": "Katana",
    "両手忍刀": "Ninja Sword",
    "両手槍": "Spear",
    "両手棒": "Pole",
    "両手ロッド": "Rod",
    "両手杖": "Staff",
    "両手弓": "Bow",
    "アロー（弓用矢）": "Arrow",
    "両手ボウガン": "Crossbow",
    "シャフト（ボウガン用矢）": "Bolt",
    "両手銃": "Gun",
    "バレット（銃用弾）": "Shot",
    "両手ハンディボム": "Hand-bomb",
    "ボム（ハンディボム用火薬）": "Bomb",
    "素手": "Unarmed",
    "Swords?Edit": "",
    "ミスリルソード": "Mythril Sword",
    "ミスリルブレイド": "Mythril Blade",
    "ブロードソード": "Broadsword",
    "ロングソード": "Longsword",
    "アイアンソード": "Iron Sword",
    "ゾーリンブレイド": "Zwill Blade",
    "古代の剣": "Ancient Sword",
    "ローエングリン": "Lohengrin",
    "フレイムタン": "Flametongue",
    "エビルスレイヤー": "Demonsbane",
    "アイスブランド": "Icebrand",
    "プラチナソード": "Platinum Sword",
    "ブラッドソード": "Blood Sword",
    "バスタードソード": "Bastard Sword",
    "ダイヤソード": "Diamond Sword",
    "ルーンブレイド": "Rune Blade",
    "デスブリンガー": "Deathbringer",
    "ブレイクブレイド": "Stoneblade",
    "デュランダル": "Durandal",
    "軍用剣": "Army Sword*",
    "ジュワユース": "Joyeuse*",
    "塵地螺鈿飾剣": "Chirijiraden*",
    "ブシドーブレイド": "Bushido Blade*",
    "Daggers?Edit": "",
    "ダガー": "Dagger",
    "メイジマッシャー": "Mage Masher",
    "アサシンダガー": "Assassin's Dagger",
    "チョッパー": "Feral Retriever",
    "マインゴージュ": "Main Gauche",
    "グラディウス": "Gladius",
    "アベンジャー": "Avenger",
    "オリハルコン": "Orichalcum Dirk",
    "プラチナメッサー": "Platinum Dagger",
    "ゾーリンシェイプ": "Zwill Crossblade",
    "ダンジューロ": "Danjuro",
    "Axes and Hammers?Edit": "",
    "ハンドアックス": "Handaxe",
    "フレイル": "Iron Hammer",
    "ブロードアックス": "Broadaxe",
    "ウォーハンマー": "War Hammer",
    "スラッシャー": "Slasher",
    "スレッジハンマー": "Sledgehammer",
    "ハンマーヘッド": "Hammerhead",
    "フランシスカ": "Francisca",
    "モーニングスター": "Morning Star",
    "グレートアックス": "Greataxe",
    "ゴールドアックス": "Golden Axe",
    "蠍のしっぽ": "Scorpion Tail",
    "Maces?Edit": "",
    "メイス": "Mace",
    "ブロンズメイス": "Bronze Maze",
    "ブージ": "Bhuj",
    "マイター": "Miter (Mitre)",
    "棘のメイス": "Thorned Mace",
    "錯乱のメイス": "Chaos Mace",
    "時限のメイス": "Doom Mace",
    "メイスオブゼウス": "Zeus Mace",
    "グランドメイス": "Grand Mace",
    "Measures?Edit": "",
    "計算尺": "Gilt Measure",
    "バルガースケール": "Arc Scale",
    "マルチスケール": "Multiscale",
    "クロススケール": "Cross Scale",
    "千分のノギス": "Caliper",
    "ユークリッド定規": "Euclid's Sextant",
    "Greatswords?Edit": "",
    "覇王の剣": "Sword of Kings",
    "契約の剣": "Treaty-Blade",
    "クレイモア": "Claymore",
    "ディフェンダー": "Defender",
    "セーブザクィーン": "Save the Queen",
    "ラグナロク": "Ragnarok",
    "アルテマブレイド": "Ultima Blade",
    "エクスカリバー": "Excalibur",
    "トウルヌソル": "Tournesol",
    "トロの剣": "Wyrmhero Blade",
    "ナイトメアー": "Nightmare*",
    "Katana?Edit": "",
    "虎徹": "Kotetsu",
    "備前長船": "Osafune",
    "小烏丸": "Kogarasumaru",
    "孫六兼元": "Magoroku",
    "村雨": "Murasame",
    "菊一文字": "Kiku-ichimonji",
    "邪迎八景": "Yakei",
    "雨のむら雲": "Ame-no-Murakumo",
    "ムラマサ": "Muramasa",
    "マサムネ": "Masamune",
    "Ninja Swords?Edit": "",
    "阿修羅": "Ashura",
    "桜囀り": "Sakura-saezuri",
    "影縫い": "Kagenui",
    "甲賀忍刀": "Koga Blade",
    "伊賀忍刀": "Iga Blade",
    "おろち": "Orochi",
    "柳生の漆黒": "Yagyu Darkblade",
    "Spears?Edit": "",
    "ジャベリン": "Javelin",
    "スピアー": "Spear",
    "パルチザン": "Partisan",
    "ヘビーランス": "Heavy Lance",
    "雷の槍": "Storm Spear",
    "オベリスク": "Obelisk",
    "ハルバード": "Halberd",
    "トライデント": "Trident",
    "ホーリーランス": "Holy Lance",
    "グングニル": "Gungnir",
    "竜の髭": "Dragon Whisker",
    "最強の矛": "Zodiac Spear",
    "Poles?Edit": "",
    "樫の棒": "Oaken Pole",
    "サイプレスパイル": "Cypress Pole",
    "バトルバンブー": "Battle Bamboo",
    "麝香勺": "Musk Stick",
    "鉄棒": "Iron Pole",
    "六角棒": "Six-fluted Pole",
    "ゴクウの棒": "Gokuu Pole",
    "エアリアル": "Aerieel",
    "象牙の棒": "Ivory Pole",
    "櫂棒": "Sweep",
    "八角棒": "Eight-fluted Pole",
    "鯨の髭": "Whale Whisker",
    "Rods?Edit": "",
    "ロッド": "Rod",
    "蛇のロッド": "Serpent Rod",
    "癒しのロッド": "Healing Rod",
    "大地のロッド": "Gaia Rod",
    "パワーロッド": "Power Rod",
    "天空のロッド": "Empyrean Rod",
    "ホーリーロッド": "Holy Rod",
    "フェイスロッド": "Rod of Faith",
    "Staves?Edit": "",
    "オークスタッフ": "Oak Staff",
    "サクラの杖": "Cherry Staff",
    "魔法使いの杖": "Wizard's Staff",
    "炎の杖": "Flame Staff",
    "雷の杖": "Storm Staff",
    "氷の杖": "Glacial Staff",
    "ゴールドスタッフ": "Golden Staff",
    "裁きの杖": "Judicer's Staff",
    "雲の杖": "Cloud Staff",
    "賢者の杖": "Staff of the Magi",
    "Bows?Edit": "",
    "ショートボウ": "Shortbow",
    "銀の弓": "Silver Bow",
    "エイビスキラー": "Aevis Killer",
    "ロングボウ": "Longbow",
    "キラーボウ": "Killer Bow",
    "エルフィンボウ": "Elfin Bow",
    "ロクスリーの弓": "Loxley Bow",
    "石の弓": "Giant Stonebow",
    "バーニングボウ": "Burning Bow",
    "裏切りの弓": "Traitor's Bow",
    "与一の弓": "Yoichi Bow",
    "ペルセウスの弓": "Perseus Bow",
    "アルテミスの弓": "Artemis Bow",
    "宿命のサジタリア": "Sagittarius",
    "Arrows?Edit": "",
    "オニオンアロー": "Onion Arrows",
    "パラレルアロー": "Parallel Arrows",
    "炎の矢": "Fiery Arrows",
    "バンブーアロー": "Bamboo Arrows",
    "雷の矢": "Lightning Arrows",
    "一撃の矢": "Assassin's Arrows",
    "凍て雲の矢": "Icecloud Arrows",
    "アルテミスの矢": "Artemis Arrows",
    "Crossbows?Edit": "",
    "ボウガン": "Bowgun",
    "クロスボウ": "Crossbow",
    "パラミナボウ": "Paramina Crossbow",
    "クロスリカーブ": "Recurve Crossbow",
    "ハンティングボウ": "Hunting Crossbow",
    "ペネトレーター": "Penetrator Crossbow",
    "ガストラフェテス": "Gastrophetes",
    "Bolts?Edit": "",
    "オニオンシャフト": "Onion Bolts",
    "ロングシャフト": "Long Bolts",
    "ストーンシャフト": "Stone Bolts",
    "鉛のクォーラル": "Lead Bolts",
    "ブラックシャフト": "Black Bolts",
    "タイムシャフト": "Time Bolts",
    "アガザイ": "Sapping Bolts",
    "グランドボルト": "Grand Bolts",
    "Guns?Edit": "",
    "アルタイル": "Altair",
    "カペラ": "Capella",
    "ヴェガ": "Vega",
    "シリウス": "Sirius",
    "ベテルギウス": "Betelgeuse",
    "ラス・アルゲテイ": "Ras Algethi",
    "アルデバラン": "Aldebaran",
    "スピカ": "Spica",
    "アンタレス": "Antares",
    "アルクトゥルス": "Arcturus",
    "フォーマルハウト": "Fomalhaut",
    "Shot?Edit": "",
    "オニオンバレット": "Onion Shot",
    "サイレント弾": "Silent Shot",
    "アクアバレット": "Aqua Shot",
    "ナパームショット": "Wyrmfire Shot",
    "ソイルショット": "Mud Shot",
    "風のペネトラテ": "Windslicer Shot",
    "ダークショット": "Dark Shot",
    "石化弾": "Stone Shot",
    "Hand-bombs?Edit": "",
    "プリニートロイデ": "Hornito",
    "ペジオニーテ": "Fumarole",
    "アスピーテ": "Tumulus",
    "マールコニーデ": "Caldera",
    "ブルカノ式": "Volcano",
    "Bombs?Edit": "",
    "オニオンボム": "Onion Bombs",
    "ポイズンボム": "Poison Bombs",
    "スタンボム": "Stun Bombs",
    "悪臭ボム": "Stink Bombs",
    "オイルボム": "Oil Bombs",
    "混乱玉": "Chaos Bombs",
    "ウォーターボム": "Water Bombs",
    "キャステラノース": "Castellanos",
    "Zodiac?versions weapons?Edit": "",
    "シカリのナガサ": "Shikari Nagasa",
    "蠍のしっぽＦ": "Vrscika",
    "マサムネＩ": "Kumbha",
    "鯨の髭Ｎ": "Kanya",
    "宿命のサジタリＡ": "Dhanusha",
    "竜の髭Ｌ": "Vrsahba",
    "シカリのナガサＦ": "Mina",
    "デュランダルＡ": "Simha",
    "おろちＮ": "Mesa",
    "ブルカノ式Ｔ": "Makara",
    "ブラッドソードＡ": "Karkata",
    "ガストラフェテＳ": "Tula",
    "アルデバランＹ": "Mithuna",
    "トランゴタワー": "Great Trango",
    "エクスカリパー": "Excalipur",
    "ぐりぐりばんばん": "Bonebreaker",
    "ビブロスの骨": "Bone of Byblos",
    "ザイテングラート": "Seitengrat",
    "Dummied Weapons?Edit": "",
    "Armor?Edit": "",
    "盾": "Shield",
    "軽装備": "Leather Armor",
    "重装備": "Heavy Armor",
    "魔装備": "Mystic Armor",
    "頭防具": "Head",
    "体防具": "Body",
    "Shields?Edit": "",
    "エスカッション": "Escutcheon",
    "皮の盾 （レザーシールド）": "Leather Shield",
    "バックラー": "Buckler",
    "ブロンズシールド": "Bronze Shield",
    "ラウンドシールド": "Round Shield",
    "ゴールドシールド": "Golden Shield",
    "アイスシールド": "Ice Shield",
    "フレイムシールド": "Flame Shield",
    "ダイヤシールド": "Diamond Shield",
    "プラチナシールド": "Platinum Shield",
    "ドラゴンシールド": "Dragon Shield",
    "クリスタルの盾": "Crystal Shield",
    "カエサルプレート": "Kaiser Shield",
    "イージスの盾": "Aegis Shield",
    "デモンズシールド": "Demon Shield",
    "ベネチアプレート": "Venetian Shield",
    "血塗られた盾": "Ensanguined Shield",
    "最強の盾": "Zodiac Escutcheon",
    "ソードブレイカー": "Swordbreaker*",
    "軒猿苦無": "Ninja Knife*",
    "Light Armor?Edit": "",
    "Head": "",
    "革の帽子": "Leather Cap",
    "ヘッドギア": "Headgear",
    "ヘッドガード": "Headguard",
    "レザーヘッドギア": "Leather Headgear",
    "角付きの帽子": "Horned Hat",
    "バラクラバ": "Balaclava",
    "ウォーワーカー": "Soldier's Cap",
    "グリーンベレー": "Green Beret",
    "レッドキャップ": "Red Cap",
    "ねじりはちまき": "Headband",
    "パイレットギア": "Pirate Hat",
    "ゴーグルマスク": "Goggle Mask",
    "アダマン帽": "Adamant Hat",
    "シャコーハット": "Officer's Hat",
    "チャクラバンド": "Chakra Band",
    "シーフの帽子": "Thief's Cap",
    "魔人の帽子": "Gigas Hat",
    "シャプロンの帽子": "Chaperon",
    "ローレルクラウン": "Crown of Laurels",
    "リジェネモリオン": "Renewing Morion",
    "デュエルマスク": "Dueling Mask",
    "Body": "",
    "革の服": "Leather Clothing",
    "クロムレザー": "Chromed Leathers",
    "レザープレイト": "Leather Breastplate",
    "ブロンズの胸当て": "Bronze Chestplate",
    "チェインプレイト": "Ringmail",
    "ポンチョ": "Windbreaker",
    "バルキーコート": "Heavy Coat",
    "サバイバルベスト": "Survival Vest",
    "ブリガンダイン": "Brigandine",
    "柔術道着": "Jujitsu Gi",
    "バイキングコート": "Viking Coat",
    "メタルジャーキン": "Metal Jerkin",
    "アダマンベスト": "Adamant Vest",
    "バレルコート": "Barrel Coat",
    "力だすき": "Power Vest",
    "忍びの衣": "Ninja Gear",
    "魔人の胸当て": "Gigas Chestplate",
    "ミネルバビスチェ": "Minerva Bustier",
    "ラバーコンシャス": "Rubber Suit",
    "ミラージュベスト": "Mirage Vest",
    "ブレイブスーツ": "Brave Suit",
    "Heavy Armor?Edit": "",
    "レザーヘルム": "Leather Helm",
    "ブロンズヘルム": "Bronze Helm",
    "サーリット": "Sallet",
    "アイアンヘルム": "Iron Helm",
    "バルビュータ": "Barbut",
    "フライングヘルム": "Winged Helm",
    "ゴールドヘルム": "Golden Helm",
    "ブルゴネット": "Burgonet",
    "クロスヘルム": "Close Helmet",
    "ボーンヘルム": "Bone Helm",
    "ダイヤヘルム": "Diamond Helm",
    "鋼鉄のダイサー": "Steel Mask",
    "プラチナヘルム": "Platinum Helm",
    "巨人の兜": "Giant's Helmet",
    "ドラゴンヘルム": "Dragon Helm",
    "魔力のシシャーク": "Magepower Shishak",
    "グランドヘルム": "Grand Helm",
    "レザーアーマー": "Leather Armor",
    "ブロンズアーマー": "Bronze Armor",
    "スケールアーマー": "Scale Armor",
    "アイアンアーマー": "Iron Armor",
    "リネンキュラッサ": "Linen Cuirass",
    "チェインメイル": "Chainmail",
    "ゴールドアーマー": "Golden Armor",
    "シールドアーマー": "Shielded Armor",
    "デモンズメイル": "Demon Mail",
    "ボーンメイル": "Bone Mail",
    "ダイヤアーマー": "Diamond Armor",
    "リクレクトメイル": "Mirror Mail",
    "プラチナアーマー": "Platinum Armor",
    "キャラビニエール": "Carabineer Mail",
    "ドラゴンメイル": "Dragon Mail",
    "マクシミリアン": "Maximillian",
    "グランドアーマー": "Grand Armor",
    "Mystic Armor?Edit": "",
    "木綿の帽子": "Cotton Cap",
    "魔法のカーチ": "Magick Curch",
    "とんがり帽子": "Pointy Hat",
    "トプカプー帽": "Topkapi Hat",
    "カロ型の帽子": "Calot Hat",
    "三角帽子": "Wizard's Hat",
    "閃光魔帽": "Lambent Hat",
    "羽根付き帽子": "Feathered Cap",
    "魔道士の帽子": "Mage's Hat",
    "ラミアのティアラ": "Lamia's Tiara",
    "魔術師の帽子": "Sorcerer's Hat",
    "黒頭巾": "Black Cowl",
    "アストラカーン": "Astrakhan Hat",
    "大地の帽子": "Gaia Hat",
    "ヒュプノクラウン": "Hypnocrown",
    "金の髪飾り": "Gold Hairpin",
    "祭司の帽子": "Celebrant's Miter",
    "黒の仮面": "Black Mask",
    "白の仮面": "White Mask",
    "黄金のスカラー": "Golden Skullcap",
    "サークレット": "Circlet",
    "木綿の服": "Cotton Shirt",
    "メディアスの服": "Light Woven Shirt",
    "シルクの服": "Silken Shirt",
    "キリム織の服": "Kilimweave Shirt",
    "羊飼いのボレロ": "Shepherd's Bolero",
    "魔法使いの服": "Wizard's Robes",
    "詠唱のジェラーバ": "Chanter's Djellaba",
    "旅人の法衣": "Traveler's Vestment",
    "魔道士の服": "Mage's Habit",
    "妖術師の服": "Enchanter's Habit",
    "魔術師の服": "Sorcerer's Habit",
    "黒装束": "Black Garb",
    "カーマニョール": "Carmagnole",
    "マディーンの衣": "Maduin Gear",
    "碧玉のガウン": "Jade Gown",
    "大地の衣": "Gaia Gear",
    "クリリカルガウン": "Cleric's Robes",
    "白のローブ": "White Robes",
    "黒のローブ": "Black Robes",
    "光のスティフォス": "Glimmering Robes",
    "ローブオブロード": "Lordly Robes",
    "Genji Set?Edit": "",
    "源氏の盾": "Genji Shield",
    "源氏の兜": "Genji Helm",
    "源氏の鎧": "Genji Armor",
    "源氏の小手": "Genji Gloves",
    "Zodiac?versions armor?Edit": "",
    "ジャンダルム": "Gendarme",
    "Accessories?Edit": "",
    "オパールの指輪": "Opal Ring",
    "ルビーの指輪": "Ruby Ring",
    "トルマリンの指輪": "Tourmaline Ring",
    "賢者の指輪": "Sage's Ring",
    "守りの指輪": "Ring of Renewal",
    "瑪瑙の指輪": "Agate Ring",
    "バングル": "Bangle",
    "オルアケアの腕輪": "Orrachea Armlet",
    "パワーリスト": "Power Armlet",
    "アーガイルの腕輪": "Argyle Armlet",
    "ダイヤの腕輪": "Diamond Armlet",
    "格闘のアンバー": "Amber Armlet",
    "アームガード": "Armguard",
    "魔法の手袋": "Magick Gloves",
    "盗賊のカフス": "Thief's Cuffs",
    "ブレイザー": "Blazer Gloves",
    "ガントレット": "Gauntlets",
    "亀のチョーカー": "Turtleshell Choker",
    "ニホパラオア": "Nihopalaoa",
    "雛のティペット": "Embroidered Tippet",
    "革のゴルゲット": "Leather Gorget",
    "ヒスイのカラー": "Jade Collar",
    "鋼のゴルゲット": "Steel Gorget",
    "薔薇のコサージュ": "Rose Corsage",
    "ほろろの根付": "Pheasant Netsuke",
    "インディゴ藍": "Indigo Pendant",
    "金のアミュレット": "Golden Amulet",
    "舫結びのガロン": "Bowline Sash",
    "ファイアフライ": "Firefly",
    "サッシュ": "Sash",
    "バブルチェーン": "Bubble Belt",
    "カメオのベルト": "Cameo Belt",
    "西陣の帯": "Nishijin Belt",
    "黒帯": "Black Belt",
    "バトルハーネス": "Battle Harness",
    "ジャックブーツ （ゲルミナスブーツ）": "Jackboots (Germinas Boots)",
    "エルメスの靴 （エルメスのくつ）": "Hermes Sandals",
    "ギリーブーツ": "Gillie Boots",
    "鋼鉄の膝当て": "Steel Poleyns",
    "フェザーブーツ": "Winged Boots",
    "クイスモイトの靴": "Quasimodo Boots",
    "ねこみみフード": "Cat-ear Hood",
    "ふわふわミトラ": "Fuzzy Miter (Fuzzy Mitre)",
    "リボン": "Ribbon",
    "人造破魔石": "Manufacted Nethicite",
    "女神の魔石": "Goddess's Magicite",
    "暁の断片": "Dawn Shard",
    "Zodiac?versions accessories?Edit": "",
    "バーサーカー": "Berserker Bracers",
    "Hunts?Edit": "",
    "対決！砂漠の赤い果実": "Red & Rotten in the Desert",
    "熱砂に現れた魔犬": "Wolf in the Waste",
    "砂風に揺れるサボテンの花": "Dalmasca's Desert Bloom",
    "地下水路に消える": "Waterway Haunting",
    "魔石鉱に生きる魔物": "Marauder in the Mines",
    "落しものにはモブがつく": "Lost in the Pudding",
    "誰がために竜はなく": "For Whom the Wyrm Tolls",
    "空から呼ぶ声": "A Scream from the Sky",
    "ピリリと苦い毒蛇の酒": "Tingling Toast",
    "衝突！オズモーネ平原を守れ！": "The Defense of Ozmone Plain",
    "流れ落ちる雨と指輪": "A Ring in the Rain",
    "死者よ、永久に眠れ": "The Dead Ought Sleep Forever",
    "神都を汚す獣の血": "Befoulment of the Beast",
    "追いかけっこは森の中": "A Chase Through the Woods",
    "邪悪な亜人、魔石鉱で何を想う": "The Mine Flayer",
    "脱走者はかたき討ちを望む": "The Deserter's Revenge",
    "地の巨人、怒りの大暴走！": "Trouble in the Hills",
    "怒りのコブシは霧をはらすか": "Adding Insult to Injury",
    "制御不能！？決死のロデオ！": "Rodeo to the Death",
    "地下宮殿の巨大亀": "Shelled Obstruction",
    "取られた荷物を取り返せ！": "Get My Stuff Back!",
    "サビた伝説、ほころびた封印": "Old Legends, Decaying Bonds",
    "人生バラ色！男の野望を目指す戦い": "The Things We Do...",
    "最高のカタログのために": "The Creature Collector",
    "死した都の墓守": "Dead City Watch",
    "地獄へのフライト！": "Visitor on Deck",
    "獄炎の悪魔は子供好き！？": "The Child Snatcher",
    "黒の魔術師": "The Black Sorcerer",
    "古代生物はワイルドな匂い！": "A Wild Stench",
    "幼き罪をつぐなうとき": "Paying for the Past",
    "邪竜、ここに目覚める": "Wyrm Wrath's Renewal",
    "最強はどっちだ！？": "Who's the Strongest!?",
    "大草原の小さな愛": "Little Love on the Big Plain",
    "魔石の力におどらされ": "The Cry of Its Power",
    "罪を許してモブは許さず！": "Crime and Punishment",
    "復活、封印されし楽園！": "Paradise Risen",
    "パラミナをかけ抜ける一陣の光": "Paramina Run",
    "異常発生アントリオン！": "Antlion Infestation",
    "私のキャロットちゃん": "Carrot Stalk",
    "ビッグブリッヂの死闘": "Battle on the Big Bridge",
    "黒いウワサ": "A Dark Rumor",
    "ミストに包まれた真実": "Truth Shrouded in Mist",
    "眠れぬ美女に安らかな夜を": "Fishy Dreams",
    "神か悪魔か": "God or Devil?",
    "最後の戦い、師よ安らかに眠れ！": "Farewell to a Legend",
    "Items?Edit": "",
    "Restorative items?Edit": "",
    "ポーション": "Potion",
    "ハイポーション": "Hi-Potion",
    "エクスポーション": "X-Potion",
    "エーテル": "Ether",
    "ハイエーテル": "Hi-Ether",
    "エリクサー": "Elixir",
    "ラストエリクサー": "Megalixir",
    "フェニックスの尾": "Phoenix Down",
    "毒消し": "Antidote",
    "金の針": "Gold Needle",
    "目薬": "Eye Drops",
    "やまびこ草": "Echo Herbs",
    "万能薬": "Remedy",
    "目覚まし時計 （王子の口づけ）": "Alarm Clock?(Prince's Kiss)",
    "あぶらとり紙": "Handkerchief",
    "クロノスの涙": "Chronos Tear",
    "気付け薬 （ン・カイの砂）": "Smelling Salts?(Nu Khai Sand)",
    "ワクチン （Ｃ９Ｈ８０４）": "Vaccine?(Serum)",
    "Offensive/Support items?Edit": "",
    "バッカスの酒": "Bacchus's Wine",
    "赤い牙 （ソレイユの牙）": "Red Fang?(Soleil Fang)",
    "青い牙 （ひょうけつの牙）": "Blue Fang?(Rime Fang)",
    "白い牙 （いかずちの牙）": "White Fang?(Lightning Fang)",
    "ダークの魔片": "Dark Mote",
    "ウォータの魔片 （アクアラの魔片）": "Water Mote (Aquara Mote)",
    "エアロの魔片": "Aero Mote",
    "ホーリーの魔片": "Holy Mote",
    "コラプスの魔片": "Scathe Mote",
    "デジョンの魔片": "Warp Mote",
    "バランスの魔片": "Balance Mote",
    "ヘイスガの魔片": "Hastega Mote",
    "リフレガの魔片": "Reflectga Mote",
    "バニシガの魔片": "Vanishga Mote",
    "レビテガの魔片": "Float Mote",
    "イクシロの実": "Eksir Berries",
    "ダークマター": "Dark Matter",
    "サビのカタマリ": "Knot of Rust",
    "下町のカルバドス": "Domaine Calvados",
    "バイオの魔片": "Bio Mote",
    "エアロガの魔片": "Aeroga Mote",
    "ショックの魔片": "Shock Mote",
    "グラビデの魔片": "Gravity Mote",
    "デスペルの魔片": "Dispel Mote",
    "ケアルラの魔片": "Cura Mote",
    "バブルの魔片": "Bubble Mote",
    "リバースの魔片": "Reverse Mote",
    "バルトロの種": "Baltoro's Seed",
    "ダークエナジー": "Dark Energy",
    "メテオライト （Ａ、Ｂ、Ｃ、Ｄ）": "Meteorite?(A, B, C, D)",
    "Loot?Edit": "",
    "アダマンタイト": "Adamantite",
    "千年亀の甲羅": "Aged Turtle Shell",
    "霊薬": "Ambrosia",
    "盤古の骨": "Ancient Bone",
    "万年亀の甲羅": "Ancient Turtle Shell",
    "南極の風": "Antarctic Wind",
    "アクエリアス": "Aquarius Gem",
    "アルカナ": "Arcana",
    "北極の風": "Arctic Wind",
    "アリエス": "Aries Gem",
    "コウモリの牙": "Bat Fang",
    "コウモリの翼": "Bat Wing",
    "攻竜の殻": "Battlewyrm Carapace",
    "獣王の皮": "Beastlord Hide",
    "獣王の角": "Beastlord Horn",
    "ベヒーモステーキ": "Behemoth Steak",
    "まがった杖": "Bent Staff",
    "ビュエルバ魂": "Bhujerban Madhu",
    "黒の珠": "Black Orb",
    "高級ウール": "Blood Wool",
    "修羅の骨": "Blood-darkened Bone",
    "血染めの首飾り": "Blood-stained Necklace",
    "ボムの灰": "Bomb Ashes",
    "ボムの欠片": "Bomb Fragment",
    "ボムの抜け殻": "Bomb Shell",
    "骨くず": "Bone Fragment",
    "オルギン": "Book of Orgain",
    "百のオルギン": "Book of Orgain-Cent",
    "千のオルギン": "Book of Orgain-Mille",
    "ウール": "Braid Wool",
    "折れた大斧": "Broken Greataxe",
    "折れた槍": "Broken Spear",
    "欠けた剣": "Broken Sword",
    "羽根の衣": "Bundle of Feathers",
    "千本針": "Bundle of Needles",
    "サボテンの実": "Cactus Fruit",
    "キャンサー": "Cancer Gem",
    "カプリコーン": "Capricorn Gem",
    "カラメル": "Caramel",
    "セントリオの英雄": "Centurio Hero's Badge",
    "落雷衝": "Charged Gizzard",
    "鉄甲殻": "Charger Barding",
    "キマイラの首": "Chimera Head",
    "チョコボの羽根": "Chocobo Feather",
    "クァールの毛皮": "Coeurl Pelt",
    "クァールのヒゲ": "Coeurl Whisker",
    "ふつうの魚": "Common Fish",
    "死虫": "Corpse Fly",
    "まがった牙": "Crooked Fang",
    "ダマスカス鋼": "Damascus Steel",
    "闇の魔晶石": "Dark Crystal",
    "闇の魔石": "Dark Magicite",
    "闇の石": "Dark Stone",
    "デスパウダー": "Death Powder",
    "シャレコウベ": "Death's Head",
    "ディモスの粘土": "Deimos Clay",
    "おいしい魚": "Delicious Fish",
    "デビルカクテル": "Demon Drink",
    "悪魔の目玉": "Demon Eyeball",
    "悪魔の羽根": "Demon Feather",
    "悪魔のため息": "Demon's Sigh",
    "悪魔のしっぽ": "Demon's Tail",
    "戦馬の殻": "Destrier Barding",
    "戦馬のたてがみ": "Destrier Mane",
    "しずく石": "Dewdrop Pebble",
    "デクアルブ": "Diakon Halcyon",
    "フカヒレ": "Dorsal Fin",
    "汚れたウール": "Drab Wool",
    "土の魔晶石": "Earth Crystal",
    "土の魔石": "Earth Magicite",
    "土の石": "Earth Stone",
    "アインヘリエル": "Einherjarium",
    "エレクトラム": "Electrum",
    "皇帝のウロコ": "Emperor Scale",
    "空きビン": "Empty Bottle",
    "霊帝の魂": "Empyreal Soul",
    "タカの眼球": "Eye of the Hawk",
    "ただれた死肉": "Festering Flesh",
    "精靈石": "Feystone",
    "良質のウール": "Fine Wool",
    "火の魔晶石": "Fire Crystal",
    "火の魔石": "Fire Magicite",
    "火の石": "Fire Stone",
    "魚のウロコ": "Fish Scale",
    "邪神の肉": "Forbidden Flesh",
    "くさった肉": "Foul Flesh",
    "くさい液": "Foul Liquid",
    "しあわせの四葉": "Four-leaf Clover",
    "カエルの油": "Frog Oil",
    "カエルのタマゴ": "Frogspawn",
    "ジェミニ": "Gemini Gem",
    "玉鋼": "Gemsteel",
    "大鳥の羽根": "Giant Feather",
    "くるくるドリル": "Gimble Stalk",
    "ガラスの宝玉": "Glass Jewel",
    "ノーマ": "Gnoma Halcyon",
    "神殺しの紋章": "Godslayer's Badge",
    "大蛇の牙": "Great Serpent's Fang",
    "大蛇の抜け殻": "Great Serpentskin",
    "緑色の液体": "Green Liquid",
    "静寂のアデド": "Grimoire Aidhed",
    "沈黙のトガル": "Grimoire Togail",
    "ギサールの野菜": "Gysahl Greens",
    "獄門の炎": "Hell-Gate's Flame",
    "大アルカナ": "High Arcana",
    "聖の魔晶石": "Holy Crystal",
    "聖の魔石": "Holy Magicite",
    "聖の石": "Holy Stone",
    "ホルアクティの炎": "Horakhty's Flame",
    "角": "Horn",
    "氷の魔晶石": "Ice Crystal",
    "氷の魔石": "Ice Magicite",
    "氷の石": "Ice Stone",
    "怪魚のウロコ": "Ichthon Scale",
    "虫の甲殻": "Insect Husk",
    "鉄の殻": "Iron Carapace",
    "鉄鉱": "Iron Ore",
    "鉄くず": "Iron Scraps",
    "カボチャのランプ": "Jack-o'-Lantern",
    "ジャヤの木片": "Jaya Stick",
    "計都の札": "Ketu Board",
    "大きな羽根": "Large Feather",
    "リョスアルブ": "Leamonde Halcyon",
    "レオ": "Leo Gem",
    "レーシー": "Leshach Halcyon",
    "リーブラ": "Libra Gem",
    "生命のロウソク": "Lifewick",
    "木材": "Lumber",
    "タイコウの紋章": "Lu Shang's Badge",
    "ウジのわいた肉": "Maggoty Flesh",
    "魔法のランプ": "Magick Lamp",
    "モルボルの花": "Malboro Flower",
    "モルボルの実": "Malboro Fruit",
    "モルボルのつる": "Malboro Vine",
    "とんかち": "Mallet",
    "マルト": "Mardu Halcyon",
    "鏡のウロコ": "Mirror Scale",
    "抜け殻": "Molting (Moulting)",
    "月の砂": "Moondust",
    "円月輪": "Moon Ring",
    "ミストルティン": "Mystletainn",
    "ミスリル": "Mythril",
    "ネブラリン": "Nebralim",
    "ネブラ産の高級魚": "Nebra Succulent",
    "オメガの紋章": "Omega Badge",
    "オニオン": "Onion",
    "オリハルク": "Orichalcum",
    "石ころ": "Pebble",
    "フォボスの上薬": "Phobos Glaze",
    "ホワイトリーフ": "Pinewood Chop",
    "パイシーズ": "Pisces Gem",
    "とがった角": "Pointed Horn",
    "高級毛皮": "Prime Pelt",
    "高級なめし革": "Prime Tanned Hide",
    "とてもくさい液": "Putrid Liquid",
    "良質の皮": "Quality Hide",
    "良質の木材": "Quality Lumber",
    "良質の毛皮": "Quality Pelt",
    "良質の石材": "Quality Stone",
    "ネズミの皮": "Rat Pelt",
    "ネズミのしっぽ": "Rat Tail",
    "虹色のタマゴ": "Rainbow Egg",
    "輪竜のキモ": "Ring Wyrm Liver",
    "輪竜のウロコ": "Ring Wyrm Scale",
    "サジタリウス": "Sagittarius Gem",
    "サラマンド": "Salamand Halcyon",
    "ブラックフェザー": "Sandalwood Chop",
    "ヒヒイロカネ": "Scarletite",
    "スコーピオ": "Scorpio Gem",
    "さけびの根": "Screamroot",
    "セム貝の貝殻": "Semclam Shell",
    "サーペンタリウス": "Serpentarius",
    "蛇眼": "Serpent Eye",
    "セーブルサイズ": "Sickle-Blade",
    "銀色の液体": "Silver Liquid",
    "天上の宝玉": "Sky Jewel",
    "スレイブハーネス": "Slaven Harness",
    "スライムオイル": "Slime Oil",
    "小さな羽根": "Small Feather",
    "たのまれた届け物": "Small Package",
    "ヘビの皮": "Snake Skin",
    "羽虫": "Snowfly",
    "大角": "Solid Horn",
    "石材": "Solid Stone",
    "ソウルオブサマサ": "Soul of Thamasa",
    "ソウルパウダー": "Soul Powder",
    "大牙": "Spiral Incisor",
    "割れた鎧": "Split Armor",
    "星の砂": "Stardust",
    "雷の魔晶石": "Storm Crystal",
    "雷の魔石": "Storm Magicite",
    "雷の石": "Storm Stone",
    "丈夫な骨": "Sturdy Bone",
    "あまい果実": "Succulent Fruit",
    "シルフス": "Sylphi Halcyon",
    "巨人のなめし革": "Tanned Giantskin",
    "なめし革": "Tanned Hide",
    "地竜のなめし革": "Tanned Tyrant Hide",
    "裂かれた衣": "Tattered Garment",
    "タウロス": "Taurus Gem",
    "テレポストーン": "Teleport Stone",
    "餓狼の生血": "Throat Wolf Blood",
    "トマトのヘタ": "Tomato Stalk",
    "亀の甲羅": "Turtle Shell",
    "地竜の骨": "Tyrant Bone",
    "地竜の皮": "Tyrant Hide",
    "ウンディーヌ": "Undin Halcyon",
    "エーテル水": "Unpurified Ether",
    "谷間の花のしずく": "Valeblossom Dew",
    "吸血の牙": "Vampyr Fang",
    "ヴァルゴ": "Virgo Gem",
    "戦神のアシュリング": "Wargod's Band",
    "水の魔晶石": "Water Crystal",
    "水の魔石": "Water Magicite",
    "水の石": "Water Stone",
    "白の香": "White Incense",
    "風の魔晶石": "Wind Crystal",
    "風の魔石": "Wind Magicite",
    "風の石": "Wind Stone",
    "風切りの羽根": "Windslicer Pinion",
    "狼の毛皮": "Wolf Pelt",
    "神々の怒り": "Wrath of the Gods",
    "死竜の骨": "Wyrm Bone",
    "竜の殻": "Wyrm Carapace",
    "飛竜の牙": "Wyvern Fang",
    "飛竜の翼": "Wyvern Wing",
    "黄色の液体": "Yellow Liquid",
    "エンサのヒレ": "Yensa Fin",
    "エンサのウロコ": "Yensa Scale",
    "ゾンビパウダー": "Zombie Powder",
    "Bazaar?Edit": "",
    "毒消しセット": "Antidote Set",
    "シンプルな上着": "Unassuming Surcoat",
    "メッキされた盾": "Gilt Shield",
    "フェニックスの尾セット": "Tail of the Phoenix",
    "かんたん救護セット": "First-aid Kit",
    "革製の防具セット": "Assorted Leathers",
    "剣山の弓矢": "Bow & Bodkin",
    "目薬セット": "Eye Drop Set",
    "狙撃用の銃弾": "Marksman's Delight",
    "軽めの槍": "Light Spear",
    "鉄でできた剣": "Iron-forged Blade",
    "ポーションセット": "Tinctures & Tonics",
    "細身のたいまつ": "Arrows Alight",
    "水玉の銃弾": "Rain of Tears",
    "木の棒": "Wooden Pole",
    "お目覚めセット": "Eye Openers",
    "赤黒い剣": "Crimson Blade",
    "旅人の装備": "Traveler's Garb",
    "金色の装備": "Golden Garb",
    "赤のコーディネイト": "Matching Reds",
    "おきづきセット": "Smelling Salts, & C.",
    "燃えている剣": "Burning Blade",
    "強めの酒": "Sipping Wine",
    "空洞の弓矢": "Hollow-shaft Arrows",
    "みがかれた防具": "Burnished Protectives",
    "燃えている牙": "Burning Fangs",
    "惑わしの衣装": "Alluring Finery",
    "格闘家の衣服": "Monk's Garb",
    "レンジャーの弓矢": "Ranger's Crossbow",
    "鉄でできた棒": "Iron-forged Pole",
    "かんたん救急セット": "Triage Kit",
    "魔法の欠片": "Magick Shard",
    "忍者の衣服": "Ninja Garb",
    "軽くて丈夫な服": "Noisome Incendiaries",
    "狩人の弓矢": "Huntsman's Crossbow",
    "ギザギザの忍刀": "Jag-tooth Ninja Sword",
    "サバイバルセット": "Survival Set",
    "不死鳥の心意気": "Soul of the Fire-bird",
    "やる気の出る防具": "Emboldening Arms",
    "プラチナ製の装備": "Platinum Gear",
    "毒の爆薬": "Noisome Incendiaries",
    "戦斧": "War Axe",
    "いびつな剣": "Warped Blade",
    "フォークのような槍": "Forked Spear",
    "土色の銃弾": "Mudslinger",
    "油の爆薬": "Oil-Soaked Incendiaries",
    "目つぶしの弓矢": "Blindflight Quarrels",
    "常備薬品セット": "Phials & Philtres",
    "ポーションボックス": "Potion Crate",
    "魔人の装備": "Gigas Gear",
    "貫通の銃弾": "Armor-piercing Shot",
    "凍った弓矢": "Permafrost Bow & Quiver",
    "かく乱用の爆薬": "Befuddling Incendiaries",
    "神秘的な杖": "Mystic Staff",
    "高級な棒": "Elegant Pole",
    "不死鳥の暴走": "Phoenix Flight",
    "黒の装備": "Black Vestments",
    "白の装備": "White Vestments",
    "植物製の防具": "Nature's Armory",
    "まがまがしい盾": "Forbidding Shield",
    "丈夫な戦闘服": "Sturdy Battle Gear",
    "魔力の兜": "Magepower Helm",
    "スカウトの弓矢": "Scout's Crossbow",
    "水玉の爆弾": "Water-drop Munitions",
    "武士の刀": "Samurai's Katana",
    "ツーヘッドナイフ": "Double-bladed Knife",
    "あざけりの剣": "The Leering Blade",
    "細身の騎士剣": "Attenuated Greatsword",
    "遠い日の思い出": "Memories of Yore",
    "破壊力のある爆薬": "Devastating Incendiaries",
    "黒鉄色の剣": "Darksteel Blade",
    "月の女神の矢": "Arrows of the Moon Goddess",
    "蛇型の忍刀": "Serpent Blade",
    "至高の一振り": "Well-forged Blade",
    "癒しのかぶり物": "Comfy Headgear",
    "化石の弾": "Stone Shot",
    "蠍": "The Scorpion",
    "銀色の弓": "Silver Bow",
    "貫きの矢": "Piercing Bolts",
    "呪われた首飾り": "Cursed Necklace",
    "魔物の髭": "Whisker of the Beast",
    "最新式の猟銃": "Late-model Rifle",
    "究極の宝剣": "Ultimate Blade",
    "月の女神の弓": "Bow of the Moon Goddess",
    "あざやかな盾": "Brilliant Shield",
    "刻印の槍": "Engraved Spear",
    "金色の戦斧": "Golden Battle Axe",
    "ヌルヌルした液体": "Flask of Oily Liquid",
    "ドロドロした液体": "Flask of Viscous Liquid",
    "聖者の秘薬": "Saint's Draught",
    "神秘の秘薬": "Esoteric Draught",
    "生命の結晶": "Life Crystal",
    "蛇の宝石": "Jewel of the Serpent",
    "大いなる存在": "Jewel of Creation",
    "至高の金属": "Matchless Metal",
    "名刀工の一品": "Master-crafted Blade",
    "ヒマワリの花": "The Sunflower",
    "しもふりの剣": "Dragon Crest",
    "謎の物体": "Mysterious Substance",
    "ポーションパック": "Potion Pack",
    "ハイポーションパック": "Hi-Potion Pack",
    "クロノスの涙パック": "Chronos Tear Pack",
    "不死鳥のささやき": "Fire-bird's Whisper",
    "ワクチンパック": "Vaccine Pack",
    "エクスポーションパック": "X-Potion Pack",
    "甲羅でできた首輪": "Shell-worked Collar",
    "忍者の靴": "Ninja Footgear",
    "格闘家の装飾品": "Brawler's Fetish",
    "弱々しい光": "Blush of Light",
    "死者の靴": "Shoes of the Dead",
    "背水のハーネス": "Back Harness",
    "大きな手袋": "Large Gloves",
    "チェーン": "Chain-link Belt",
    "はやての靴": "Wind Walkers",
    "鳥のストラップ": "Wing Cord",
    "金色の装飾品": "Gilt Phylactery",
    "きらびやかな腕輪": "Exquisite Ring",
    "羽根の生えた靴": "Feathered Boots",
    "古びた書物": "Forgotten Gromoire",
    "おぞましい壺": "Morbid Urn",
    "Key items?Edit": "",
    "エンゲージ・デッド": "Accursed Trophy",
    "エンゲージ・ソリッド": "Adamantine Trophy",
    "ぼろぼろのカギ": "Age-Worn Key",
    "長女からの手紙": "Ann's Letter",
    "金色に光る手紙": "Auric Message",
    "バルハイムのカギ": "Barheim Key",
    "エンゲージ・ビーク": "Beaked Trophy",
    "黒色のボトル": "Black Bottle",
    "すすけたかけら": "Blackened Fragment",
    "青色のボトル": "Blue Bottle",
    "エンゲージ・スケル": "Bony Trophy",
    "壊れたカギ": "Broken Key",
    "サボテンの契り": "Cactoid Commendation",
    "サボテンの印": "Cactoid Compact",
    "サボテンの花": "Cactus Flower",
    "カノープスの壷": "Canopic Jar",
    "エンゲージ・クロウ": "Clawed Trophy",
    "クレセントストーン": "Crescent Stone",
    "エンゲージ・サッド": "Cruel Trophy",
    "竜のうろこ": "Dragon Scale",
    "竜騎士の心得": "Dragoon's Monograph",
    "くすんだかけら": "Dull Fragment",
    "空き家の手紙": "Dusty Letter",
    "エンゲージ・ブラッド": "Ensanguined Trophy",
    "エルモネアの葉": "Errmonea Leaf",
    "エンゲージ・エタニティ": "Eternal Trophy",
    "エンゲージ・ファング": "Fanged Trophy",
    "愛の羽根": "Feather of the Flock",
    "エンゲージ・フラッター": "Feathered Trophy",
    "エンゲージ・イービル": "Fell Trophy",
    "エンゲージ・フィアー": "Frigid Trophy",
    "エンゲージ・ファー": "Fur-scaled Trophy",
    "ガルバナの花": "Galbana Lilies",
    "最長老のおみやげ": "Gift of the Great-Chief",
    "エンゲージ・ヘル": "Gravesoul Trophy",
    "緑色のボトル": "Green Bottle",
    "緑色に光る手紙": "Green-Hued Message",
    "よごれたかけら": "Grimy Fragment",
    "エンゲージ・スケイル": "Hide-Covered Trophy",
    "狩人の心得": "Hunter's Monograph",
    "ナイトの心得": "Knight's Monograph",
    "研究所のカード": "Lab Access Card",
    "エンゲージ・ウィング": "Leathern Trophy",
    "レンテの涙": "Lente's Tear",
    "力なき力のメダル": "Lustreless Medallion",
    "魔道士の心得": "Mage's Monograph",
    "エンゲージ・ギャロップ": "Maned Trophy",
    "マタムネ": "Matamune",
    "エンゲージ・ハフ": "Maverick Trophy",
    "勇気のメダル": "Medallion of Bravery",
    "愛のメダル": "Medallion of Love",
    "力のメダル": "Medallion of Might",
    "技家の腕章": "Merchant's Armband",
    "エンゲージ・ミミック": "Metallic Trophy",
    "エンゲージ・ブレイン": "Mind Trophy",
    "月銀のメダル": "Moonsilver Medallion",
    "ムラマタ": "Muramata",
    "第１営倉のカギ": "No. 1 Brig Key",
    "エンゲージ・スメル": "Odiferous Trophy",
    "漆黒に光る手紙": "Onyx Message",
    "ピリカの日記": "Pilika's Diary",
    "ラビットテイル": "Rabbit's Tail",
    "赤色のボトル": "Red Bottle",
    "エンゲージ・レプタイル": "Reptillian Trophy",
    "キルティアの指輪": "Ring of the Light",
    "カエルの指輪": "Ring of the Toad",
    "朽ちた鎧の破片": "Rusted Scrap of Armor",
    "賢者の心得": "Sage's Monograph",
    "学者の心得": "Scholar's Monograph",
    "エンゲージ・カッター": "Scythe Trophy",
    "蛇酒の素": "Serpentwyne Must",
    "陰石": "Shadestone",
    "エンゲージ・シェル": "Shelled Trophy",
    "エンゲージ・シクル": "Sickle Trophy",
    "沈黙の壷": "Silent Urn",
    "第３鉱区のカギ": "Site 3 Key",
    "第１１鉱区のカギ": "Site 11 Key",
    "エンゲージ・フレーム": "Skull Trophy",
    "エンゲージ・ゲル": "Slimy Trophy",
    "水門のカギ": "Sluice Gate Key",
    "封魂のカギ": "Soul Ward Key",
    "エンゲージ・ソウル": "Soulless Trophy",
    "盗まれた品": "Stolen Articles",
    "断罪の魔石": "Stone of the Condemner",
    "太陽石": "Sunstone",
    "ダルマスカ剣": "Sword of the Order",
    "システム制御キー": "Systems Access Key",
    "ヒューズ管": "Tube Fuse",
    "エンゲージ・ファンシー": "Vengeful Trophy",
    "真紅に光る手紙": "Vermillion Message",
    "ヴィエラの荷物": "Viera Rucksack",
    "エンゲージ・クリミナル": "Vile Trophy",
    "青白く光る手紙": "Wanly-Limed Message",
    "魔剣士の心得": "Warmage's Monograph",
    "エンゲージ・ウィスカー": "Whiskered Trophy",
    "風の方位輪": "Wind Globe",
    "風読のコンパス": "Wind Vane",
    "トマジの伝票 （あずかった伝票）": "Writ of Transit",
    "黄色のボトル": "Yellow Bottle",
    "Enemies?Edit": "",
    "タイニーサボテン": "Cactite",
    "ウルフリーダー": "Alpha Wolf",
    "ワイルドザウルス": "Wild Saurian",
    "コカトリス": "Cockatrice",
    "ハイエナ": "Hyena",
    "ハイエナリーダー": "Alpha Hyena",
    "ウールゲーター": "Wooly Gator",
    "ギーザラビット": "Giza Rabbit",
    "オズモヘア": "Ozmone Hare",
    "ランドタートル": "Great Tortoise",
    "ジルコンタートル": "Silicon Tortoise",
    "ワイルドスネーク": "Wildsnake",
    "ウェアウルフ": "Werewolf",
    "ウェアラット": "Dire Rat",
    "実験用ラット": "Lab Rat",
    "バリトンダイル": "Baritine Croc",
    "ギガントード": "Gigantoad",
    "グレートキング": "Malboro Overking",
    "ガルキマセラ": "Garchimacera",
    "ゲシュンペスト": "Gespenst",
    "水のカオスジュダ": "Water Chaosjet",
    "ライジングビスト": "Suriander",
    "タイニーミミック": "Tiny Mimic",
    "タイニーバグ": "Tiny Bug",
    "バッテリミミック": "Battery Mimic",
    "スペクター": "Specter?(Spectre)",
    "タイニーバッテリ": "Tiny Battery",
    "プレゼンター": "Mimeo",
    "スカルアーマー": "Skull Defender",
    "デッドリーボーン": "Dead Bones",
    "ヴァンパイア": "Vampyr",
    "キラーマンティス": "Killer Mantis",
    "デュラハン": "Dullahan",
    "バグ": "Bug",
    "ダークロード": "Dark Lord",
    "パンドラ": "Pandora",
    "ゲイザー": "Gazer",
    "アルラウネ": "Alraune",
    "ダンバニア": "Danbania",
    "ダンバニアリード": "Bull Danbania",
    "アックスビーク": "Axebeak",
    "エンサリーダー": "Bull Yensa",
    "ワイバーン": "Wyvern",
    "ワイバーンリード": "Bellwyvern",
    "シーカーバット": "Seeker",
    "ロストソウル": "Lost Soul",
    "ミニマムキマイラ": "Lesser Chimera",
    "ゾンビメイジ": "Zombie Mage",
    "スカルウォリアー": "Skull Warrior",
    "リッチ": "Lich",
    "ラゴウ": "Ragoh",
    "キャンドル": "Tallow",
    "メズマライズ": "Mesmenir",
    "赤チョコボ": "Red Chocobo",
    "黒チョコボ": "Black Chocobo",
    "白チョコボ": "White Chocobo",
    "茶チョコボ": "Brown Chocobo",
    "緑チョコボ": "Green Chocobo",
    "赤チョコボＬｖ９９": "Lv.99 Red Chocobo",
    "ウー": "Wu",
    "ズー": "Zu",
    "ヴァイパー": "Viper",
    "ザグナル": "Zaghnal",
    "クロスゲーター": "Hybrid Gator",
    "パンサー": "Panther",
    "トレント": "Treant",
    "ヘルハウンド": "Hellhound",
    "ウェアドラゴン": "Diresaur",
    "モルボルグレート": "Great Malboro",
    "サンダーバグ": "Thunderbug",
    "ゼリー": "Jelly",
    "ロックイーター": "Tyranorox",
    "ヘクトアイズ": "Hecteyes",
    "ギザマルーク": "Gizamaluk",
    "エテム": "Et?m",
    "ネクロマンサー": "Necrofiend",
    "ホワイトウルフ": "White Wolf",
    "ツインタニア": "Twintania",
    "リザード": "Lizard",
    "エイビスエンペラ": "Emperor Aevis",
    "ガルーダ": "Garuda",
    "ガルーダ・エギ": "Garuda-Egi",
    "ダークスケルトン": "Dark Skeleton",
    "スレイヴキャプ": "Slaven Warder",
    "スカルナイト": "Skull Knight",
    "イエティ": "Yeti",
    "氷のアーゼ": "Ice Azer",
    "マッドオニオン": "Wild Onion",
    "レッドマウス": "Redmaw",
    "ゾンビファイター": "Zombie Warrior",
    "ヒルギガース": "Blood Gigas",
    "ナイトウォーカー": "Nightwalker",
    "パワーオブパワー": "Reaper Claw",
    "パワーオブマナ": "Reaper Mage",
    "ドラゴンエイビス": "Dragon Aevis",
    "グール": "Ghoul",
    "ダークメア": "Darkmare",
    "バルーン": "Balloon",
    "ミリアムガード": "Miriam Guardian",
    "オイルタワー": "Oiling",
    "ミリアムフェイス": "Miriam Facer",
    "ガスト": "Ghast",
    "ウォーグウルフ": "Worgen",
    "ウォーグリーダー": "Alpha Worgen",
    "フンババ": "Humbaba",
    "パイソン": "Python",
    "アッシュドラゴン": "Ash Wyrm",
    "ヴァルチャー": "Vulture",
    "クレイゴーレム": "Clay Golem",
    "ディコタイタス": "Slaven Wilder",
    "火のカオスジュダ": "Fire Chaosjet",
    "フォーチュンラビ": "Wyrdhare",
    "パンプキンヘッド": "Pumpkin Head",
    "スプリンター": "Sprinter",
    "モルボルキング": "Malboro King",
    "シルバリオ": "Silver Lobo",
    "シュメルケ": "Iguion",
    "アルケオダイノス": "Archaeosaur",
    "ピロリスク": "Pyrolisk",
    "ピラニア": "Piranha",
    "バドゥ": "Bagoly",
    "風のカオスジュダ": "Air Chaosjet",
    "ワイルドダイル": "Feral Croc",
    "土のカオスジュダ": "Earth Chaosjet",
    "アビス": "Abysteel",
    "インプ": "Imp",
    "ストライカー": "Striker",
    "ピットフィーンド": "Pit Fiend",
    "ウェンディゴ": "Wendigo",
    "ゾンビナイト": "Zombie Knight",
    "ゴーキマイラ": "Gorgimera",
    "フォカロル": "Focalor",
    "ケルベロス": "Cerberus",
    "キラートマト": "Deadly Nightshade",
    "ムー": "Mu",
    "マンドラプリンス": "Mandragora Prince",
    "バジリスク": "Basilisk",
    "キングアルラウネ": "Alraune King",
    "オニオンクイーン": "Onion Queen",
    "マンティスデビル": "Preying Mantis",
    "パンプキンスター": "Pumpkin Star",
    "トマトキャプテン": "Topstalk",
    "ミラーナイト": "Mirrorknight",
    "タルタロス": "Tartarus",
    "オセ": "Ose",
    "シェイド": "Shadonir",
    "ギルヴェガノス": "Giruveganus",
    "スカルドラゴン": "Skulwyrm",
    "ヴィヴィアン": "Vivian",
    "ライフフォビドン": "Forbidden",
    "バロン": "Gargoyle Baron",
    "マザーグレネード": "Mom Bomb",
    "ミスリルゴーレム": "Mythril Golem",
    "ネクロフォビア": "Necrophobe",
    "デスクロウ": "Deathclaw",
    "キャシー": "Cassie",
    "アバドン": "Abaddon",
    "アバドンリーダー": "Bull Abaddon",
    "キマイラブレイン": "Chimera Brain",
    "ブーネ": "Bune",
    "マジックポット": "Magick Pot",
    "アパンダ": "Reaver",
    "アパンダリーダー": "High Reaver",
    "クルセイダー": "Crusader",
    "アイロネート": "Aeronite",
    "ドラゴンゾンビ": "Dragon Lich",
    "スラストエイビス": "Cataract Aevis",
    "コジャ": "Brainpan",
    "ピュロボロス": "Purobolos",
    "デイダラ": "Deidar",
    "スプラッシュ": "Stomp",
    "リーチフロッグ": "Speartongue",
    "グレネード": "Grenade",
    "キラーカッター": "Scythe Mantis",
    "スライム": "Slime",
    "アルケオエイビス": "Archaeoaevis",
    "ボギー": "Bogey",
    "メリッサ": "Mallicant",
    "コープス": "Shambling Corpse",
    "ブエル": "Buer",
    "アダマンタイタス": "Adamantitan",
    "ガルピュデス": "Charybterix",
    "バンデルクァール": "Bandercoeurl",
    "シールドドラゴン": "Shield Wyrm",
    "エメラルタス": "Emeralditan",
    "ウルタンイーター": "Urutan Eater",
    "ワイアード": "Leynir",
    "バンシー": "Banshee",
    "フォーバー": "Foobar",
    "オーバーソウル": "Oversoul",
    "バブイル": "Babil",
    "エルヴィオレ": "Elvoret",
    "ウォーロック": "Zombie Warlock",
    "Marks?Edit": "",
    "はぐれトマト": "Rogue Tomato",
    "アトモス": "Atomos",
    "テクスタ": "Thextera",
    "ロビー": "Roblon",
    "花サボテン": "Flowering Cactoid",
    "ブライ": "Braegh",
    "レイス": "Wraith",
    "ダークスティール": "Darksteel",
    "ニーズヘッグ": "Nidhogg",
    "ヴィラール": "Vyraal",
    "ホワイトムース": "White Mousse",
    "リンドヴルム": "Lindwyrm",
    "リングドラゴン": "Ring Wyrm",
    "オーバーロード": "Overlord",
    "ワイバーンロード": "Wyvern Lord",
    "ゴリアテ": "Goliath",
    "マリリス": "Marilith",
    "デスサイズ": "Deathscythe",
    "エンケドラス": "Enkelados",
    "デスゲイズ": "Deathgaze",
    "ケロゲロス": "Croakadile",
    "ディアボロス": "Diabolos",
    "イシュタム": "Ixtab",
    "ピスコディーモン": "Piscodaemon",
    "ワイルドモルボル": "Wild Malboro",
    "ボーパルバニー": "Vorpal Bunny",
    "カトブレパス": "Catoblepas",
    "マインドフレア": "Mindflayer",
    "ファーヴニル": "Fafnir",
    "ブラッディ": "Bloodwing",
    "パイルラスタ": "Pylraster",
    "Elite Marks?Edit": "",
    "ヒナドリス": "Chickatrice",
    "ニワトリス": "Cluckatrice",
    "ロックタイタス": "Rocktoise",
    "オルトロス": "Orthros",
    "ギルガメ": "Gil Snapper",
    "トリックスター": "Trickster",
    "アントリオン": "Antlion",
    "キャロット": "Carrot",
    "ギルガメッシュ": "Gilgamesh",
    "エンキドゥ": "Enkidu",
    "ベリト": "Belito",
    "キングベヒーモス": "Behemoth King",
    "イクシオン": "Ixion",
    "パンデモニウム": "Pandaemonium",
    "シャーリート": "Slyt",
    "フェンリル": "Fenrir",
    "フェニックス": "Phoenix",
    "闇神": "Shadowseer",
    "ヤズマット": "Yiazmat",
    "Rare Game?Edit": "",
    "アスピドケロン": "Aspidochelon",
    "フェニレンス": "Thalassinon",
    "アヌビス": "Anubys",
    "グリード": "Greeden",
    "バルムー": "Barmuu",
    "ブルダイル": "Bull Croc",
    "ヴィシュヌ": "Vishno",
    "ガビアル": "Gavial",
    "イセリアル": "Etherian",
    "カウンターウルフ": "Wary Wolf",
    "メルティゼリー": "Melt",
    "カイザーウルフ": "Kaiser Wolf",
    "カブス": "Cubus",
    "リンブルウルフ": "Lindbur Wolf",
    "パイナップル": "Pineapple",
    "ドレッドガード": "Dreadguard",
    "ブリット": "Bombshell",
    "クリプトバニー": "Crypt Bunny",
    "ヒュージボム": "Megabomb",
    "スピィ": "Spee",
    "パイダーボム": "Matriarch Bomb",
    "レインダンサー": "Rain Dancer",
    "ランペイジャー": "Ripe Rampager",
    "レイザーフィン": "Razorfin",
    "キリング": "Killbug",
    "アプサラス": "Apsara",
    "ミニマムバグ": "Minibug",
    "レイジクロウ": "Rageclaw",
    "ターゲッター": "Ithuno",
    "バイドカッター": "Biding Mantis",
    "クリス": "Kris",
    "スニークフロッグ": "Wood Toad",
    "ディード": "Dheed",
    "タラスク": "Tarasque",
    "エアロス": "Aeros",
    "グリマルキン": "Grimalkin",
    "スケアクロウ": "Terror Tyrant",
    "ネクベト": "Nekhbet",
    "アベリスク": "Abelisk",
    "グレアリングアイ": "Glaring Eye",
    "ダスティア": "Dustia",
    "キャルトリッチ": "Cultsworn Lich",
    "イスティーン": "Ishteen",
    "イビルスピリット": "Evil Spirit",
    "ヴォーレス": "Vorres",
    "ジャガーノート": "Juggernaut",
    "ネガルムル": "Negalmuur",
    "アムスティ": "Molen",
    "ラルヴァイーター": "Larva Eater",
    "タワー": "Tower",
    "アリオク": "Arioch",
    "バルトヴァイパー": "Grey Molter",
    "フィディル": "Fideliant",
    "ミドガルズオルム": "Midgardsormr",
    "クリスタルナイト": "Crystal Knight",
    "ナザルニル": "Nazarnir",
    "グレイブロード": "Grave Lord",
    "ヴィクター": "Victanir",
    "ゾンビロード": "Zombie Lord",
    "ジュエルホーン": "Gemhorn",
    "ドゥラウナ": "Drowned",
    "ライトオブライト": "Luxollid",
    "ヴェレル": "Velelu",
    "ソウルオブカオス": "Vagrant Soul",
    "ディズマ": "Disma",
    "イムドゥグド": "Imdugud",
    "アンクボルダー": "Ancbolder",
    "チョコボリーダー": "Bull Chocobo",
    "ウェンディス": "Wendice",
    "スカルアッシュ": "Skullash",
    "アンクハガー": "Anchag",
    "マイス": "Myath",
    "ブルーブラッド": "Bluesang",
    "ヘルヴィネック": "Helvinek",
    "アヴェンジャー": "Avenger",
    "パル": "Pallicant",
    "アルティック": "Alteci",
    "フィロー": "Phyllo",
    "Bosses?Edit": "",
    "ブッシュファイア": "Bushfire",
    "ラフレシア": "Rafflesia",
    "ミミッククィーン": "Mimic Queen",
    "ダイダロス": "Daedalus",
    "ギジュー": "Gijuk",
    "ブワジ": "Bwagi",
    "リノ": "Rinok",
    "タイラント": "Tyrant",
    "デモンズウォール": "Demon Wall",
    "ハイドロ": "Hydro",
    "ティアマット": "Tiamat",
    "アースドラゴン": "Earth Tyrant",
    "エルダードラゴン": "Elder Wyrm",
    "フューリー": "Fury",
    "ヴィヌスカラ": "Vinuskar",
    "フンババボス": "Humbaba Mistant",
    "ボムキング": "King Bomb",
    "魔神竜": "Hell Wyrm",
    "アーリマン": "Ahriman",
    "オメガｍｋ．ＸＩＩ": "Omega Mark XII",
    "山賊シーク": "Seeq Cateran",
    "盗賊シーク": "Seeq Thief",
    "シーク族の探検家": "Seeq Explorer",
    "ダグザ": "Daguza",
    "ガリドー": "Galeedo",
    "グイッチ": "Gwitch",
    "ウルタンエンサ族（素手）": "Urutan-Yensa*",
    "ウルタンエンサ族（両手刀）": "Urutan-Yensa*",
    "ウルタンエンサ族（両手弓）": "Urutan-Yensa*",
    "ガリフ族の冒険者": "Garif Adventurer",
    "バクナムス族（素手）": "Baknamy*",
    "バクナムス族（片手剣）": "Baknamy*",
    "バクナムス族（銃）": "Baknamy*",
    "盗賊バンガ": "Bangaa Thief",
    "海賊バンガ": "Bangaa Pirate",
    "バンガ族の格闘家": "Bangaa Pugilist",
    "帝国軍剣士": "Imperial Swordsman",
    "帝国軍銃士": "Imperial Marksman",
    "帝国軍重兵士": "Imperial Hoplite",
    "帝国軍魔導士": "Imperial Magus",
    "軍用犬": "Mastiff",
    "ジャッジ・ギース": "Judge Ghis",
    "帝国軍ガンナー": "Imperial Gunner",
    "帝国軍突撃兵": "Imperial Pilot",
    "帝国軍操獣士": "Imperial Beastmaster",
    "ジャッジ・ベルガ": "Judge Bergan",
    "小型飛空艇レモラ": "Air Cutter Remora",
    "ルークスピナー": "Spinner-Rook",
    "ルークスフィア": "Sphere-Rook",
    "ルークメット": "Helm-Rook",
    "ルーク": "Rook",
    "ガブラス": "Gabranth",
    "ドクター・シド": "Doctor Cid",
    "ヴェイン": "Vayne",
    "ヴェイン＝ノウス": "Vayne Novus",
    "セフィラ": "Sephira",
    "不滅なるもの": "The Undying",
    "Enemy abilities?Edit": "",
    "ウォタラ": "Watera?(Aquara)",
    "エアロラ": "Aerora",
    "ウォタガ": "Waterga?(Aquaga)",
    "ファイジャ": "Firaja",
    "サンガー": "Thundaja",
    "ブリザジャ": "Blizzaja",
    "クエイジャ": "Quakeja",
    "ウォタジャ": "Waterja",
    "エアロジャ": "Aeroja",
    "ホーリジャ": "Holyja",
    "ダージャ": "Darkja",
    "ドンムブガ": "Immobilizega",
    "ドンアクガ": "Disablega",
    "フィアー": "Fear",
    "フィアガ": "Fearga",
    "フォーグ": "Fog",
    "アンチ": "Invert",
    "カーズ": "Curse",
    "バケアル": "Pox",
    "ダテレポ": "Telega",
    "ファントムペイン": "Breakart Pentagram",
    "レベル２睡眠": "Level 2 Sleep",
    "レベル３ドンアク": "Level 3 Disable",
    "レベル４ブレイク": "Level 4 Break",
    "レベル５逆転": "Level 5 Reverse",
    "レベル素数デス": "Prime Level Death",
    "必殺": "Death Strike",
    "貫通デスペガ": "Piercing Dispelga",
    "貫通ホーリー": "Piercing Holy",
    "貫通ファイガ": "Piercing Firaga",
    "貫通サンダガ": "Piercing Thundaga",
    "貫通ブリザガ": "Piercing Blizzaga",
    "貫通グラビガ": "Piercing Graviga",
    "アースシェイク": "Temblor",
    "蒼ノ波動": "Azure Vortice",
    "紅ノ波動": "Crimson Vortice",
    "アクアバブル": "Aqua Bubbles",
    "アクアハリケーン": "Water Spout",
    "アグレッサー": "Enrage",
    "アセンション": "Ascension",
    "圧縮密砲": "Nectar Volley",
    "あまい息": "Cloying Breath",
    "怒りの一撃": "Smite of Rage",
    "行けエンキドゥ！": "Fly, Enkidu!",
    "イノセンス": "Innocence",
    "祈りの歌": "Vespersong",
    "今だエンキドゥ！": "Now, Enkidu!",
    "ウィングスピア": "Wing Spear",
    "ウェーブパルサー": "Pulsar Wave",
    "ウォータレイ": "Water Ray",
    "うさスラッガー": "Bunny Slam",
    "うなる": "Growl",
    "エアスクリュー": "Screwtail",
    "英雄マーチ": "Hero's March",
    "エグゼクション": "Guilt",
    "Ｓ２７式魔砲": "S-27 Tokamak",
    "Ｓ８５式炸裂魔砲": "S-85 Cyclotrone",
    "王者の剣": "Monarch Sword",
    "大暴れ": "Rage",
    "押しつぶす": "Flatten",
    "快音波": "Joyous Soundwave",
    "怪音波": "Eerie Soundwave",
    "戒律": "Inviolable Will",
    "火炎": "Flame Breath",
    "カタスト": "Force Barrier",
    "活性": "Purify",
    "花粉": "Pollen",
    "かみつき": "Gnaw",
    "気合い": "Battle Cry",
    "ギガフレアソード": "Gigaflare Sword",
    "究極幻想": "Ultimate Illusion",
    "吸血": "Leech",
    "驚異": "Growing Threat",
    "くさい息": "Bad Breath",
    "クラウン": "Crown",
    "クラッシュファング": "Crushing Fangs",
    "グランドシェイク": "Ground Shaker",
    "黒の衝撃": "Dark Shock",
    "ケの宣告": "Boon",
    "蹴り": "Kick",
    "限界突破": "Limit Break",
    "幻惑のまなざし": "Phantasmal Gaze",
    "ゴブリンアタック": "Goblin Attack",
    "コルドブレイク": "Ice Break",
    "サイクロン": "Cyclone",
    "嶄然震撼": "Force of Will",
    "サンダーストーム": "Thunderstorm",
    "サンダーバースト": "Shockstorm",
    "三段斬り": "Slice Thrice",
    "シオウルスポール": "Sporefall",
    "死の宣告": "Doom",
    "自爆": "Self-Destruct",
    "シャイニングレイ": "Shining Ray",
    "しゃくり": "Rush",
    "しゃくりあげ": "Heave",
    "ジャッジマント": "Circle of Judgment",
    "ジャッジメント": "Judgment",
    "ジャンプ": "Jump",
    "集中": "Focus",
    "充電": "Charge",
    "消化液": "Bile",
    "衝撃波": "Blast Wave",
    "ショックウェーブ": "Shock Wave",
    "頭突き": "Ram",
    "捨て身": "Self-Sacrifice",
    "ストンプレス": "Stone Stomp",
    "スネークウィップ": "Snake Lash",
    "スパイラルカット": "Spiral Cut",
    "スリプルタッチ": "Sleep Touch",
    "スワップテイル": "Tail Swipe",
    "生命の息吹": "Breath of Life",
    "セーバー": "Sabre",
    "石化にらみ": "Stone Gaze",
    "絶叫": "Scream",
    "絶対防御": "Perfect Defense",
    "セフィラの大樹": "Tree of Sephira",
    "センテンス": "Sentence",
    "旋風": "Gust",
    "創種": "Spawn",
    "ソードダンス": "Sword Dance",
    "束縛解放": "Unleash",
    "ソニックスピン": "Sonic Spin",
    "ソニックターン": "Sonic Turn",
    "ソニックファング": "Sonic Fangs",
    "ダークネス": "Darkness",
    "体当たり": "Lunge",
    "大ジャンプ": "High Jump",
    "大絶叫": "Wail",
    "大旋風": "Gale",
    "大突進": "Dash",
    "タカの瞳": "Hawk Glare",
    "戦いの歌": "Warsong",
    "多段蹴り": "Flurry Kick",
    "魂のエチュード": "Soul Etude",
    "断罪": "Contempt",
    "治癒": "Renew",
    "挑発": "Provoke",
    "チョコメット": "Choco-Comet",
    "猪突猛進": "Wild Charge",
    "治療": "Restore",
    "つっつき": "Poke",
    "ディバインソード": "Divine Sword",
    "ディメンジョン": "Dimensional Rift",
    "テイルスピア": "Tail Spear",
    "デッドダイブ": "Kamikaze",
    "デビルブラスター": "Hell Blaster",
    "テラフレア": "Teraflare",
    "天使の詩": "Angelsong",
    "テンペスト": "Tempest",
    "時のレクイエム": "Time Requiem",
    "とてもくさい息": "Putrid Breath",
    "トライアタック": "Tri-Attack",
    "仲間呼び": "Cry for Help",
    "ネクロマンシー": "Necromancy",
    "粘着液": "Mucus",
    "バオル": "Greater Barrier",
    "爆導索": "Chain Reaction",
    "パニックボイス": "Screech",
    "バマジク": "Magick Barrier",
    "バリアチェンジ": "Shift",
    "パワースタン": "Power Stun",
    "パワーターン": "Power Spin",
    "バンダルカッター": "Spike Cutter",
    "ひっかき": "Rake",
    "ヒットジエンド": "Bitter End",
    "ヒップアタック": "Flank Attack",
    "ビンタ": "Slap",
    "ファイアボール": "Fire Ball",
    "ファング": "Fangs",
    "プチブレス": "Ember Breath",
    "ブラスター": "Blaster",
    "フラッシュ": "Flash",
    "ブレイクタッチ": "Stone Touch",
    "フレイムロード": "Pyromania",
    "ブレス": "Breath",
    "分裂": "Divide",
    "ペトロブレス": "Stone Breath",
    "ポイズンタッチ": "Poison Touch",
    "ポイズンブレス": "Poison Breath",
    "胞子乱舞": "Pollen Dance",
    "放電": "Discharge",
    "ボーン": "Bone Toss",
    "捕食": "Cannibalize",
    "ホワイトブレス": "White Breath",
    "マインドウィップ": "Mind Lash",
    "マジックバラード": "Magick Ballad",
    "マシンガン": "Blitz Tongue",
    "魔審銃": "Gatling Gun",
    "マッハウェイヴ": "Mach Wave",
    "マッハパンチ": "Mach Punch",
    "魔力の泉": "Mana Spring",
    "回し蹴り": "Spinkick",
    "水鉄砲": "Water Cannon",
    "ミステリーワルツ": "Mystery Waltz",
    "ミスリルバブル": "Mythril Bubbles",
    "無の指先": "Annul",
    "瞑想": "Meditate",
    "メーザーアイ": "Maser Eye",
    "メガフレア": "Megaflare",
    "めった斬り": "Eviscerator",
    "誘爆": "Mass-Destruct",
    "ラッシュ": "Pummel",
    "レモラボム": "Remora Strike",
    "連続魔": "Chain Magick",
    "ロッククラッシュ": "Tremor",
    "Enemy Augments?Edit": "",
    "Names of these abilities are not listed in the game and are from the?Final Fantasy XII Battle Ultimania?and?Final Fantasy XII Piggyback The Complete Guide.": "",
    "セーフティ": "Safety",
    "魔法障壁": "Paling",
    "完全マバリア": "Anti-Magick",
    "白の風": "White Wind",
    "ノックバック無効": "No Knockback",
    "銃・計算尺耐性": "Resist Guns/Measures",
    "活力無視": "Ignore Vitality",
    "天候＆地形無視": "Ignore Weather & Landscape",
    "リフレク貫通": "Ignore Reflect",
    "回避無視": "Ignore Evade",
    "通常攻撃ダメージＵＰ": "Normal Damage+",
    "ＨＰ消費攻撃": "HP Attack",
    "盾強化": "Shield+",
    "見切り": "Evade+",
    "カウンター": "Counter",
    "カウンター確率ＵＰ": "Counter+",
    "被ダメージ返し": "Reflect Damage",
    "被ダメージカット": "Reduce Damage",
    "消費ＭＰ半減": "Half MP",
    "消費ＭＰ０": "0 MP",
    "通常攻撃ＣＴ０": "Attack CT0",
    "魔法ＣＴ０": "Magick CT0",
    "薬の知識": "Medicine Lore",
    "薬の効果逆転": "Reverse Medicine",
    "Elements?Edit": "",
    "火": "Fire",
    "氷": "Ice",
    "雷": "Lightning",
    "水": "Water",
    "土": "Earth",
    "風": "Wind",
    "聖": "Holy",
    "闇": "Dark",
    "Status effects?Edit": "",
    "Negative?Edit": "",
    "不明": "X-Zone",
    "戦闘不能": "KO",
    "石化": "Stone",
    "石化中": "Petrify",
    "混乱": "Confuse",
    "睡眠": "Sleep",
    "ウイルス": "Disease",
    "逆転": "Reverse",
    "沈黙": "Silence",
    "くらやみ": "Blind",
    "猛毒": "Poison",
    "スリップ": "Sap",
    "瀕死": "HP Critical",
    "Positive?Edit": "",
    "おとり": "Lure",
    "透明": "Invisible",
    "浮遊": "Float",
    "狂戦士": "Berserk",
    "Traps?Edit": "",
    "爆発": "Explosion",
    "ステンニードル": "Sten Needle",
    "サドンバースト": "Fusillade",
    "ウィザードキル": "Wizardbane",
    "ヒル": "Leech",
    "石化ガス": "Stone Gas",
    "錯乱ガス": "Befuddling Gas",
    "沈黙ガス": "Silence Gas",
    "窒息ガス": "Choking Gas",
    "催涙煙": "Blinding Smoke",
    "パラライズ": "Stasis",
    "ムカデ": "Swarm",
    "アブラムシ": "Oil Bug",
    "小金喰虫": "Gil Bug",
    "HP回復": "Rejuvenation",
    "MP回復": "Manafont",
    "Weather and terrain?Edit": "",
    "晴れ": "Sunny",
    "くもり": "Cloudy",
    "雨": "Rain",
    "大雨": "Heavy Rain",
    "雪": "Snow",
    "吹雪": "Snowstorm",
    "霧": "Fog",
    "濃霧": "Dense Fog",
    "砂嵐": "Sandstorm",
    "砂": "Sand",
    "Terms?Edit": "",
    "ハントループ": "Hunt Club",
    "天候": "Weather",
    "地形": "Terrain",
    "カテゴリー": "Genus",
    "タイプ": "Class",
    "Zodiac?versions jobs?Edit": "",
    "白魔道士": "White Mage",
    "ウーラン": "Uhlan",
    "機工士": "Machinist",
    "赤魔戦士": "Red Battlemage",
    "ナイト": "Knight",
    "モンク": "Monk",
    "時空魔戦士": "Time Battlemage",
    "ブレイカー": "Foebreaker",
    "弓使い": "Archer",
    "黒魔道士": "Black Mage",
    "もののふ": "Bushi",
    "シカリ": "Shikari"
  }
